// Command wireroutes generates Go route formats from the checked-in OpenAPI paths.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

var parameter = regexp.MustCompile(`\{[^{}]+\}`)

func main() {
	check := flag.Bool("check", false, "fail when generated routes differ")
	flag.Parse()
	const source = "api/openapi.yaml"
	const target = "pkg/tuya/internal/wire/routes.gen.go"
	data, err := os.ReadFile(source)
	if err != nil {
		fatal(err)
	}
	routes, err := parseRoutes(string(data))
	if err != nil {
		fatal(err)
	}
	generated, err := generate(routes)
	if err != nil {
		fatal(err)
	}
	if *check {
		if err := checkSourceRoutes(routes); err != nil {
			fatal(err)
		}
		current, err := os.ReadFile(target)
		if err != nil {
			fatal(err)
		}
		if !bytes.Equal(current, generated) {
			fatal(fmt.Errorf("%s is stale; run go run ./tools/wireroutes", target))
		}
		return
	}
	if err := os.WriteFile(target, generated, 0644); err != nil {
		fatal(err)
	}
}

func checkSourceRoutes(routes []route) error {
	known := make(map[string]bool)
	missing := make(map[string]bool)
	for _, route := range routes {
		known[normalizeRoute(route.path)] = true
	}
	files, err := filepath.Glob("pkg/tuya/*.go")
	if err != nil {
		return err
	}
	for _, filename := range files {
		if strings.HasSuffix(filename, "_test.go") {
			continue
		}
		file, err := parser.ParseFile(token.NewFileSet(), filename, nil, 0)
		if err != nil {
			return err
		}
		ast.Inspect(file, func(node ast.Node) bool {
			literal, ok := node.(*ast.BasicLit)
			if !ok || literal.Kind != token.STRING {
				return true
			}
			value, err := strconv.Unquote(literal.Value)
			if err != nil {
				return true
			}
			start := regexp.MustCompile(`/v[0-9]+\.[0-9]+/`).FindStringIndex(value)
			if start == nil {
				return true
			}
			path := strings.SplitN(value[start[0]:], "?", 2)[0]
			if !known[normalizeRoute(path)] {
				missing[fmt.Sprintf("%s: %s", filename, path)] = true
			}
			return true
		})
	}
	if len(missing) > 0 {
		var entries []string
		for entry := range missing {
			entries = append(entries, entry)
		}
		sort.Strings(entries)
		return fmt.Errorf("routes absent from api/openapi.yaml:\n  %s", strings.Join(entries, "\n  "))
	}
	return nil
}

func normalizeRoute(path string) string {
	path = parameter.ReplaceAllString(path, "{}")
	path = strings.ReplaceAll(path, "%s", "{}")
	path = strings.ReplaceAll(path, "%v", "{}")
	return path
}

type route struct {
	id     string
	method string
	path   string
}

func parseRoutes(content string) ([]route, error) {
	var routes []route
	var path, method string
	inPaths := false
	for _, line := range strings.Split(content, "\n") {
		if line == "paths:" {
			inPaths = true
			continue
		}
		if !inPaths {
			continue
		}
		if line != "" && line[0] != ' ' && line[0] != '#' {
			break
		}
		if strings.HasPrefix(line, "  /") && strings.HasSuffix(strings.TrimSpace(line), ":") {
			path = strings.TrimSuffix(strings.TrimSpace(line), ":")
			method = ""
			continue
		}
		if strings.HasPrefix(line, "    ") && !strings.HasPrefix(line, "     ") && strings.HasSuffix(strings.TrimSpace(line), ":") {
			candidate := strings.TrimSuffix(strings.TrimSpace(line), ":")
			switch candidate {
			case "get", "post", "put", "patch", "delete", "head", "options":
				method = strings.ToUpper(candidate)
			default:
				method = ""
			}
			continue
		}
		if method != "" && strings.HasPrefix(line, "      operationId:") {
			id := strings.Trim(strings.TrimSpace(strings.TrimPrefix(strings.TrimSpace(line), "operationId:")), "\"'")
			if id == "" || path == "" {
				return nil, fmt.Errorf("operation without path or ID")
			}
			routes = append(routes, route{id: id, method: method, path: path})
			method = ""
		}
	}
	if len(routes) == 0 {
		return nil, fmt.Errorf("no OpenAPI operations found")
	}
	return routes, nil
}

func generate(routes []route) ([]byte, error) {
	sort.Slice(routes, func(i, j int) bool { return routes[i].id < routes[j].id })
	var out strings.Builder
	out.WriteString("// Code generated by tools/wireroutes from api/openapi.yaml; DO NOT EDIT.\n")
	out.WriteString("package wire\n\nconst (\n")
	seen := make(map[string]bool)
	for _, route := range routes {
		name := "Route" + strings.ToUpper(route.id[:1]) + route.id[1:]
		if seen[name] {
			return nil, fmt.Errorf("duplicate operation ID: %s", route.id)
		}
		seen[name] = true
		format := parameter.ReplaceAllString(route.path, "%s")
		fmt.Fprintf(&out, "\t%s = %q\n", name, format)
		fmt.Fprintf(&out, "\tMethod%s = %q\n", strings.TrimPrefix(name, "Route"), route.method)
	}
	out.WriteString(")\n")
	return format.Source([]byte(out.String()))
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
