// Package tuyamodels provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package tuyamodels

import (
	"encoding/json"
	"fmt"
)

// Defines values for JSONMediaType.
const (
	JSONMediaTypeApplicationJSON JSONMediaType = "application/json"
)

// Valid indicates whether the value is a known member of the JSONMediaType enum.
func (e JSONMediaType) Valid() bool {
	switch e {
	case JSONMediaTypeApplicationJSON:
		return true
	default:
		return false
	}
}

// JSONMediaType Implementation-derived JSON media type used by the QR authentication headers.
type JSONMediaType string

// LoginCodeEnvelope Tuya response envelope observed by the library. Unspecified envelope fields are retained.
type LoginCodeEnvelope struct {
	// Code Provider response code when present.
	Code *int `json:"code,omitempty"`

	// Msg Provider response message when present.
	Msg *string `json:"msg,omitempty"`

	// Result Login token payload observed by the library.
	Result *LoginCodeResult `json:"result,omitempty"`

	// Success Whether the operation succeeded, when present.
	Success *bool `json:"success,omitempty"`

	// T Provider response timestamp when present.
	T *int64 `json:"t,omitempty"`

	// Tid Provider trace identifier when present.
	Tid                  *string                `json:"tid,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// LoginCodeResult Login token payload observed by the library.
type LoginCodeResult struct {
	AccessToken          *string                `json:"access_token,omitempty"`
	Endpoint             *string                `json:"endpoint,omitempty"`
	ExpireTime           *int64                 `json:"expire_time,omitempty"`
	RefreshToken         *string                `json:"refresh_token,omitempty"`
	TerminalId           *string                `json:"terminal_id,omitempty"`
	Uid                  *string                `json:"uid,omitempty"`
	Username             *string                `json:"username,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// QRCodeEnvelope Tuya response envelope observed by the library. Unspecified envelope fields are retained.
type QRCodeEnvelope struct {
	// Code Provider response code when present.
	Code *int `json:"code,omitempty"`

	// Msg Provider response message when present.
	Msg *string `json:"msg,omitempty"`

	// Result QR login payload observed by the library.
	Result *QRCodeResult `json:"result,omitempty"`

	// Success Whether the operation succeeded, when present.
	Success *bool `json:"success,omitempty"`

	// T Provider response timestamp when present.
	T *int64 `json:"t,omitempty"`

	// Tid Provider trace identifier when present.
	Tid                  *string                `json:"tid,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// QRCodeResult QR login payload observed by the library.
type QRCodeResult struct {
	Qrcode               *string                `json:"qrcode,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// RefreshTokenEnvelope Tuya response envelope observed by the library. Unspecified envelope fields are retained.
type RefreshTokenEnvelope struct {
	// Code Provider response code when present.
	Code *int `json:"code,omitempty"`

	// Msg Provider response message when present.
	Msg *string `json:"msg,omitempty"`

	// Result Refresh-token payload observed by the library.
	Result *RefreshedTokenResult `json:"result,omitempty"`

	// Success Whether the operation succeeded, when present.
	Success *bool `json:"success,omitempty"`

	// T Provider response timestamp when present.
	T *int64 `json:"t,omitempty"`

	// Tid Provider trace identifier when present.
	Tid                  *string                `json:"tid,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// RefreshedTokenResult Refresh-token payload observed by the library.
type RefreshedTokenResult struct {
	AccessToken          *string                `json:"accessToken,omitempty"`
	ExpireTime           *int64                 `json:"expireTime,omitempty"`
	RefreshToken         *string                `json:"refreshToken,omitempty"`
	Uid                  *string                `json:"uid,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// GenerateLoginQRCodeParams defines parameters for GenerateLoginQRCode.
type GenerateLoginQRCodeParams struct {
	// Clientid Configured Tuya client identifier.
	Clientid string `form:"clientid" json:"clientid"`

	// Usercode Home Assistant authorization access code.
	Usercode string `form:"usercode" json:"usercode"`

	// Schema Authentication schema; defaults to the package constant.
	Schema string `form:"schema" json:"schema"`

	// ContentType JSON response content type requested by this implementation.
	ContentType JSONMediaType `json:"Content-Type"`
}

// ValidateLoginCodeParams defines parameters for ValidateLoginCode.
type ValidateLoginCodeParams struct {
	// Clientid Configured Tuya client identifier.
	Clientid string `form:"clientid" json:"clientid"`

	// Usercode Home Assistant authorization access code.
	Usercode string `form:"usercode" json:"usercode"`

	// ContentType JSON response content type requested by this implementation.
	ContentType JSONMediaType `json:"Content-Type"`
}

// Getter for additional properties for LoginCodeEnvelope. Returns the specified
// element and whether it was found
func (a LoginCodeEnvelope) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for LoginCodeEnvelope
func (a *LoginCodeEnvelope) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for LoginCodeEnvelope to handle AdditionalProperties
func (a *LoginCodeEnvelope) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["code"]; found {
		err = json.Unmarshal(raw, &a.Code)
		if err != nil {
			return fmt.Errorf("error reading 'code': %w", err)
		}
		delete(object, "code")
	}

	if raw, found := object["msg"]; found {
		err = json.Unmarshal(raw, &a.Msg)
		if err != nil {
			return fmt.Errorf("error reading 'msg': %w", err)
		}
		delete(object, "msg")
	}

	if raw, found := object["result"]; found {
		err = json.Unmarshal(raw, &a.Result)
		if err != nil {
			return fmt.Errorf("error reading 'result': %w", err)
		}
		delete(object, "result")
	}

	if raw, found := object["success"]; found {
		err = json.Unmarshal(raw, &a.Success)
		if err != nil {
			return fmt.Errorf("error reading 'success': %w", err)
		}
		delete(object, "success")
	}

	if raw, found := object["t"]; found {
		err = json.Unmarshal(raw, &a.T)
		if err != nil {
			return fmt.Errorf("error reading 't': %w", err)
		}
		delete(object, "t")
	}

	if raw, found := object["tid"]; found {
		err = json.Unmarshal(raw, &a.Tid)
		if err != nil {
			return fmt.Errorf("error reading 'tid': %w", err)
		}
		delete(object, "tid")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for LoginCodeEnvelope to handle AdditionalProperties
func (a LoginCodeEnvelope) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Code != nil {
		object["code"], err = json.Marshal(a.Code)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'code': %w", err)
		}
	}

	if a.Msg != nil {
		object["msg"], err = json.Marshal(a.Msg)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'msg': %w", err)
		}
	}

	if a.Result != nil {
		object["result"], err = json.Marshal(a.Result)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'result': %w", err)
		}
	}

	if a.Success != nil {
		object["success"], err = json.Marshal(a.Success)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'success': %w", err)
		}
	}

	if a.T != nil {
		object["t"], err = json.Marshal(a.T)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 't': %w", err)
		}
	}

	if a.Tid != nil {
		object["tid"], err = json.Marshal(a.Tid)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'tid': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for LoginCodeResult. Returns the specified
// element and whether it was found
func (a LoginCodeResult) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for LoginCodeResult
func (a *LoginCodeResult) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for LoginCodeResult to handle AdditionalProperties
func (a *LoginCodeResult) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["access_token"]; found {
		err = json.Unmarshal(raw, &a.AccessToken)
		if err != nil {
			return fmt.Errorf("error reading 'access_token': %w", err)
		}
		delete(object, "access_token")
	}

	if raw, found := object["endpoint"]; found {
		err = json.Unmarshal(raw, &a.Endpoint)
		if err != nil {
			return fmt.Errorf("error reading 'endpoint': %w", err)
		}
		delete(object, "endpoint")
	}

	if raw, found := object["expire_time"]; found {
		err = json.Unmarshal(raw, &a.ExpireTime)
		if err != nil {
			return fmt.Errorf("error reading 'expire_time': %w", err)
		}
		delete(object, "expire_time")
	}

	if raw, found := object["refresh_token"]; found {
		err = json.Unmarshal(raw, &a.RefreshToken)
		if err != nil {
			return fmt.Errorf("error reading 'refresh_token': %w", err)
		}
		delete(object, "refresh_token")
	}

	if raw, found := object["terminal_id"]; found {
		err = json.Unmarshal(raw, &a.TerminalId)
		if err != nil {
			return fmt.Errorf("error reading 'terminal_id': %w", err)
		}
		delete(object, "terminal_id")
	}

	if raw, found := object["uid"]; found {
		err = json.Unmarshal(raw, &a.Uid)
		if err != nil {
			return fmt.Errorf("error reading 'uid': %w", err)
		}
		delete(object, "uid")
	}

	if raw, found := object["username"]; found {
		err = json.Unmarshal(raw, &a.Username)
		if err != nil {
			return fmt.Errorf("error reading 'username': %w", err)
		}
		delete(object, "username")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for LoginCodeResult to handle AdditionalProperties
func (a LoginCodeResult) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.AccessToken != nil {
		object["access_token"], err = json.Marshal(a.AccessToken)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'access_token': %w", err)
		}
	}

	if a.Endpoint != nil {
		object["endpoint"], err = json.Marshal(a.Endpoint)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'endpoint': %w", err)
		}
	}

	if a.ExpireTime != nil {
		object["expire_time"], err = json.Marshal(a.ExpireTime)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'expire_time': %w", err)
		}
	}

	if a.RefreshToken != nil {
		object["refresh_token"], err = json.Marshal(a.RefreshToken)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'refresh_token': %w", err)
		}
	}

	if a.TerminalId != nil {
		object["terminal_id"], err = json.Marshal(a.TerminalId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'terminal_id': %w", err)
		}
	}

	if a.Uid != nil {
		object["uid"], err = json.Marshal(a.Uid)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'uid': %w", err)
		}
	}

	if a.Username != nil {
		object["username"], err = json.Marshal(a.Username)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'username': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for QRCodeEnvelope. Returns the specified
// element and whether it was found
func (a QRCodeEnvelope) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for QRCodeEnvelope
func (a *QRCodeEnvelope) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for QRCodeEnvelope to handle AdditionalProperties
func (a *QRCodeEnvelope) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["code"]; found {
		err = json.Unmarshal(raw, &a.Code)
		if err != nil {
			return fmt.Errorf("error reading 'code': %w", err)
		}
		delete(object, "code")
	}

	if raw, found := object["msg"]; found {
		err = json.Unmarshal(raw, &a.Msg)
		if err != nil {
			return fmt.Errorf("error reading 'msg': %w", err)
		}
		delete(object, "msg")
	}

	if raw, found := object["result"]; found {
		err = json.Unmarshal(raw, &a.Result)
		if err != nil {
			return fmt.Errorf("error reading 'result': %w", err)
		}
		delete(object, "result")
	}

	if raw, found := object["success"]; found {
		err = json.Unmarshal(raw, &a.Success)
		if err != nil {
			return fmt.Errorf("error reading 'success': %w", err)
		}
		delete(object, "success")
	}

	if raw, found := object["t"]; found {
		err = json.Unmarshal(raw, &a.T)
		if err != nil {
			return fmt.Errorf("error reading 't': %w", err)
		}
		delete(object, "t")
	}

	if raw, found := object["tid"]; found {
		err = json.Unmarshal(raw, &a.Tid)
		if err != nil {
			return fmt.Errorf("error reading 'tid': %w", err)
		}
		delete(object, "tid")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for QRCodeEnvelope to handle AdditionalProperties
func (a QRCodeEnvelope) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Code != nil {
		object["code"], err = json.Marshal(a.Code)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'code': %w", err)
		}
	}

	if a.Msg != nil {
		object["msg"], err = json.Marshal(a.Msg)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'msg': %w", err)
		}
	}

	if a.Result != nil {
		object["result"], err = json.Marshal(a.Result)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'result': %w", err)
		}
	}

	if a.Success != nil {
		object["success"], err = json.Marshal(a.Success)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'success': %w", err)
		}
	}

	if a.T != nil {
		object["t"], err = json.Marshal(a.T)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 't': %w", err)
		}
	}

	if a.Tid != nil {
		object["tid"], err = json.Marshal(a.Tid)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'tid': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for QRCodeResult. Returns the specified
// element and whether it was found
func (a QRCodeResult) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for QRCodeResult
func (a *QRCodeResult) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for QRCodeResult to handle AdditionalProperties
func (a *QRCodeResult) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["qrcode"]; found {
		err = json.Unmarshal(raw, &a.Qrcode)
		if err != nil {
			return fmt.Errorf("error reading 'qrcode': %w", err)
		}
		delete(object, "qrcode")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for QRCodeResult to handle AdditionalProperties
func (a QRCodeResult) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Qrcode != nil {
		object["qrcode"], err = json.Marshal(a.Qrcode)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'qrcode': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for RefreshTokenEnvelope. Returns the specified
// element and whether it was found
func (a RefreshTokenEnvelope) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for RefreshTokenEnvelope
func (a *RefreshTokenEnvelope) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for RefreshTokenEnvelope to handle AdditionalProperties
func (a *RefreshTokenEnvelope) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["code"]; found {
		err = json.Unmarshal(raw, &a.Code)
		if err != nil {
			return fmt.Errorf("error reading 'code': %w", err)
		}
		delete(object, "code")
	}

	if raw, found := object["msg"]; found {
		err = json.Unmarshal(raw, &a.Msg)
		if err != nil {
			return fmt.Errorf("error reading 'msg': %w", err)
		}
		delete(object, "msg")
	}

	if raw, found := object["result"]; found {
		err = json.Unmarshal(raw, &a.Result)
		if err != nil {
			return fmt.Errorf("error reading 'result': %w", err)
		}
		delete(object, "result")
	}

	if raw, found := object["success"]; found {
		err = json.Unmarshal(raw, &a.Success)
		if err != nil {
			return fmt.Errorf("error reading 'success': %w", err)
		}
		delete(object, "success")
	}

	if raw, found := object["t"]; found {
		err = json.Unmarshal(raw, &a.T)
		if err != nil {
			return fmt.Errorf("error reading 't': %w", err)
		}
		delete(object, "t")
	}

	if raw, found := object["tid"]; found {
		err = json.Unmarshal(raw, &a.Tid)
		if err != nil {
			return fmt.Errorf("error reading 'tid': %w", err)
		}
		delete(object, "tid")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for RefreshTokenEnvelope to handle AdditionalProperties
func (a RefreshTokenEnvelope) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Code != nil {
		object["code"], err = json.Marshal(a.Code)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'code': %w", err)
		}
	}

	if a.Msg != nil {
		object["msg"], err = json.Marshal(a.Msg)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'msg': %w", err)
		}
	}

	if a.Result != nil {
		object["result"], err = json.Marshal(a.Result)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'result': %w", err)
		}
	}

	if a.Success != nil {
		object["success"], err = json.Marshal(a.Success)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'success': %w", err)
		}
	}

	if a.T != nil {
		object["t"], err = json.Marshal(a.T)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 't': %w", err)
		}
	}

	if a.Tid != nil {
		object["tid"], err = json.Marshal(a.Tid)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'tid': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for RefreshedTokenResult. Returns the specified
// element and whether it was found
func (a RefreshedTokenResult) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for RefreshedTokenResult
func (a *RefreshedTokenResult) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for RefreshedTokenResult to handle AdditionalProperties
func (a *RefreshedTokenResult) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["accessToken"]; found {
		err = json.Unmarshal(raw, &a.AccessToken)
		if err != nil {
			return fmt.Errorf("error reading 'accessToken': %w", err)
		}
		delete(object, "accessToken")
	}

	if raw, found := object["expireTime"]; found {
		err = json.Unmarshal(raw, &a.ExpireTime)
		if err != nil {
			return fmt.Errorf("error reading 'expireTime': %w", err)
		}
		delete(object, "expireTime")
	}

	if raw, found := object["refreshToken"]; found {
		err = json.Unmarshal(raw, &a.RefreshToken)
		if err != nil {
			return fmt.Errorf("error reading 'refreshToken': %w", err)
		}
		delete(object, "refreshToken")
	}

	if raw, found := object["uid"]; found {
		err = json.Unmarshal(raw, &a.Uid)
		if err != nil {
			return fmt.Errorf("error reading 'uid': %w", err)
		}
		delete(object, "uid")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for RefreshedTokenResult to handle AdditionalProperties
func (a RefreshedTokenResult) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.AccessToken != nil {
		object["accessToken"], err = json.Marshal(a.AccessToken)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'accessToken': %w", err)
		}
	}

	if a.ExpireTime != nil {
		object["expireTime"], err = json.Marshal(a.ExpireTime)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'expireTime': %w", err)
		}
	}

	if a.RefreshToken != nil {
		object["refreshToken"], err = json.Marshal(a.RefreshToken)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'refreshToken': %w", err)
		}
	}

	if a.Uid != nil {
		object["uid"], err = json.Marshal(a.Uid)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'uid': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
