generate:
  models: true
output: pkg/dependencymodels/common.gen.go
output-options:
  exclude-schemas:
    - DeviceCommand
    - DeviceDetailsEnvelope
    - DeviceListByUserEnvelope
    - DeviceListEnvelope
    - DeviceListResult
    - DeviceLogRecord
    - DeviceLogsEnvelope
    - DeviceLogsResult
    - DeviceRecord
    - DeviceSpecification
    - DeviceSpecificationEnvelope
    - DeviceStatus
    - DeviceStatusEnvelope
    - DeviceStatusMapping
    - DeviceStatusResult
    - DeviceUserBody
    - DeviceUserEnvelope
    - DeviceUserRecord
    - DeviceUsersEnvelope
    - EncryptedDataEnvelope
    - EncryptedHTTPResponseEnvelope
    - EncryptedRequestHeaders
    - FactoryInfoRecord
    - FactoryInfosEnvelope
    - HomeDevicesEnvelope
    - HomeListEnvelope
    - HomeRecord
    - LoginCodeEnvelope
    - LoginCodeResult
    - MessageQueueConfigBody
    - MessageQueueConfigEnvelope
    - MessageQueueConfiguration
    - MessageQueueSubscription
    - MessageQueueTopic
    - MultiOutletNameRecord
    - MultiOutletNamesEnvelope
    - QRCodeEnvelope
    - QRCodeResult
    - RTCOfferBody
    - RTCSessionEnvelope
    - RTCSessionResult
    - RawDeviceManagementBizData
    - RawDeviceManagementData
    - RawDeviceReportData
    - RawDeviceStatusChange
    - RawSharingMessage
    - RawSharingMessageData
    - RefreshTokenEnvelope
    - RefreshedTokenResult
    - SendCommandsBody
    - SpecificationFunction
    - SpecificationStatus
    - SubDeviceRecord
    - SubDevicesEnvelope
    - UpdateMultiOutletNameBody
    - UpdateNameBody
  include-operation-ids:
    - __component_only__
  skip-prune: true
package: tuyamodels
