// Package tuyamodels provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package tuyamodels

import (
	"encoding/json"
	"fmt"
)

// Defines values for RawSharingMessageProtocol.
const (
	N20 RawSharingMessageProtocol = 20
	N4  RawSharingMessageProtocol = 4
)

// Valid indicates whether the value is a known member of the RawSharingMessageProtocol enum.
func (e RawSharingMessageProtocol) Valid() bool {
	switch e {
	case N20:
		return true
	case N4:
		return true
	default:
		return false
	}
}

// RawSharingMessage Compatibility projection of the former generic MQTT message envelope. Active runtime decoding uses the protocol-discriminated RawSharingEvent variants.
type RawSharingMessage struct {
	// Data Compatibility projection of the former merged protocol 4 and protocol 20 data shape. Active event decoding uses RawDeviceReportData or RawDeviceManagementData according to the outer protocol value.
	Data RawSharingMessageData `json:"data"`

	// Protocol Compatibility projection of the former combined MQTT message protocol enum. Active event decoding uses RawSharingEvent and its protocol-specific envelope types.
	Protocol             RawSharingMessageProtocol `json:"protocol"`
	T                    *int64                    `json:"t,omitempty"`
	AdditionalProperties map[string]interface{}    `json:"-"`
}

// RawSharingMessageData Compatibility projection of the former merged protocol 4 and protocol 20 data shape. Active event decoding uses RawDeviceReportData or RawDeviceManagementData according to the outer protocol value.
type RawSharingMessageData struct {
	BizCode *string `json:"bizCode,omitempty"`

	// BizData Implementation-derived, extensible business payload for MQTT management events.
	BizData              *RawDeviceManagementBizData `json:"bizData,omitempty"`
	DataId               *string                     `json:"dataId,omitempty"`
	DevId                *string                     `json:"devId,omitempty"`
	ProductKey           *string                     `json:"productKey,omitempty"`
	Status               *[]RawDeviceStatusChange    `json:"status,omitempty"`
	Ts                   *int64                      `json:"ts,omitempty"`
	AdditionalProperties map[string]interface{}      `json:"-"`
}

// RawSharingMessageProtocol Compatibility projection of the former combined MQTT message protocol enum. Active event decoding uses RawSharingEvent and its protocol-specific envelope types.
type RawSharingMessageProtocol int

// Getter for additional properties for RawSharingMessage. Returns the specified
// element and whether it was found
func (a RawSharingMessage) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for RawSharingMessage
func (a *RawSharingMessage) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for RawSharingMessage to handle AdditionalProperties
func (a *RawSharingMessage) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["data"]; found {
		err = json.Unmarshal(raw, &a.Data)
		if err != nil {
			return fmt.Errorf("error reading 'data': %w", err)
		}
		delete(object, "data")
	}

	if raw, found := object["protocol"]; found {
		err = json.Unmarshal(raw, &a.Protocol)
		if err != nil {
			return fmt.Errorf("error reading 'protocol': %w", err)
		}
		delete(object, "protocol")
	}

	if raw, found := object["t"]; found {
		err = json.Unmarshal(raw, &a.T)
		if err != nil {
			return fmt.Errorf("error reading 't': %w", err)
		}
		delete(object, "t")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for RawSharingMessage to handle AdditionalProperties
func (a RawSharingMessage) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["data"], err = json.Marshal(a.Data)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'data': %w", err)
	}

	object["protocol"], err = json.Marshal(a.Protocol)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'protocol': %w", err)
	}

	if a.T != nil {
		object["t"], err = json.Marshal(a.T)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 't': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for RawSharingMessageData. Returns the specified
// element and whether it was found
func (a RawSharingMessageData) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for RawSharingMessageData
func (a *RawSharingMessageData) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for RawSharingMessageData to handle AdditionalProperties
func (a *RawSharingMessageData) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["bizCode"]; found {
		err = json.Unmarshal(raw, &a.BizCode)
		if err != nil {
			return fmt.Errorf("error reading 'bizCode': %w", err)
		}
		delete(object, "bizCode")
	}

	if raw, found := object["bizData"]; found {
		err = json.Unmarshal(raw, &a.BizData)
		if err != nil {
			return fmt.Errorf("error reading 'bizData': %w", err)
		}
		delete(object, "bizData")
	}

	if raw, found := object["dataId"]; found {
		err = json.Unmarshal(raw, &a.DataId)
		if err != nil {
			return fmt.Errorf("error reading 'dataId': %w", err)
		}
		delete(object, "dataId")
	}

	if raw, found := object["devId"]; found {
		err = json.Unmarshal(raw, &a.DevId)
		if err != nil {
			return fmt.Errorf("error reading 'devId': %w", err)
		}
		delete(object, "devId")
	}

	if raw, found := object["productKey"]; found {
		err = json.Unmarshal(raw, &a.ProductKey)
		if err != nil {
			return fmt.Errorf("error reading 'productKey': %w", err)
		}
		delete(object, "productKey")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if raw, found := object["ts"]; found {
		err = json.Unmarshal(raw, &a.Ts)
		if err != nil {
			return fmt.Errorf("error reading 'ts': %w", err)
		}
		delete(object, "ts")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for RawSharingMessageData to handle AdditionalProperties
func (a RawSharingMessageData) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.BizCode != nil {
		object["bizCode"], err = json.Marshal(a.BizCode)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'bizCode': %w", err)
		}
	}

	if a.BizData != nil {
		object["bizData"], err = json.Marshal(a.BizData)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'bizData': %w", err)
		}
	}

	if a.DataId != nil {
		object["dataId"], err = json.Marshal(a.DataId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'dataId': %w", err)
		}
	}

	if a.DevId != nil {
		object["devId"], err = json.Marshal(a.DevId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'devId': %w", err)
		}
	}

	if a.ProductKey != nil {
		object["productKey"], err = json.Marshal(a.ProductKey)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'productKey': %w", err)
		}
	}

	if a.Status != nil {
		object["status"], err = json.Marshal(a.Status)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'status': %w", err)
		}
	}

	if a.Ts != nil {
		object["ts"], err = json.Marshal(a.Ts)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'ts': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
