generate:
  models: true
output: pkg/dependencymodels/homes.gen.go
output-options:
  exclude-schemas:
    - AuthenticationOrigin
    - BooleanResultEnvelope
    - CloudAPIOrigin
    - CloudRegion
    - DeviceCommand
    - DeviceDetailsEnvelope
    - DeviceListByUserEnvelope
    - DeviceListEnvelope
    - DeviceListResult
    - DeviceLogRecord
    - DeviceLogsEnvelope
    - DeviceLogsResult
    - DeviceRecord
    - DeviceSpecification
    - DeviceSpecificationEnvelope
    - DeviceStatus
    - DeviceStatusEnvelope
    - DeviceStatusMapping
    - DeviceStatusResult
    - DeviceUserBody
    - DeviceUserEnvelope
    - DeviceUserRecord
    - DeviceUsersEnvelope
    - EncryptedDataEnvelope
    - EncryptedHTTPResponseEnvelope
    - EncryptedRequestHeaders
    - EncryptedRequestQuery
    - EncryptedSignatureHeaderOrder
    - EncryptedSignatureHeaderPairTemplate
    - EncryptedSignatureHeaderSeparator
    - EncryptedSignaturePayloadTemplate
    - FactoryInfoRecord
    - FactoryInfosEnvelope
    - JSONMediaType
    - LoginCodeEnvelope
    - LoginCodeResult
    - MessageQueueConfigBody
    - MessageQueueConfigEnvelope
    - MessageQueueConfiguration
    - MessageQueueSubscription
    - MessageQueueTopic
    - MultiOutletNameRecord
    - MultiOutletNamesEnvelope
    - QRCodeEnvelope
    - QRCodeResult
    - QRCodeTokenPrefix
    - RTCOfferBody
    - RTCSessionEnvelope
    - RTCSessionResult
    - RawDeviceManagementBizData
    - RawDeviceManagementData
    - RawDeviceReportData
    - RawDeviceStatusChange
    - RawSharingMessage
    - RawSharingMessageData
    - RefreshTokenEnvelope
    - RefreshedTokenResult
    - SendCommandsBody
    - SpecificationFunction
    - SpecificationStatus
    - StringResultEnvelope
    - SubDeviceRecord
    - SubDevicesEnvelope
    - TuyaBizCode
    - TuyaDataPointCode
    - TuyaDeviceCategory
    - TuyaErrorEnvelope
    - UpdateMultiOutletNameBody
    - UpdateNameBody
  include-operation-ids:
    - queryHomes
    - queryHomeDevices
  skip-prune: true
package: tuyamodels
