// Package tuyamodels provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package tuyamodels

import (
	"encoding/json"
	"fmt"
)

// HomeDevicesEnvelope Tuya response envelope observed by the library. Unspecified envelope fields are retained.
type HomeDevicesEnvelope struct {
	// Code Provider response code when present.
	Code *int `json:"code,omitempty"`

	// Msg Provider response message when present.
	Msg    *string         `json:"msg,omitempty"`
	Result *[]DeviceRecord `json:"result,omitempty"`

	// Success Whether the operation succeeded, when present.
	Success *bool `json:"success,omitempty"`

	// T Provider response timestamp when present.
	T *int64 `json:"t,omitempty"`

	// Tid Provider trace identifier when present.
	Tid                  *string                `json:"tid,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// HomeListEnvelope Tuya response envelope observed by the library. Unspecified envelope fields are retained.
type HomeListEnvelope struct {
	// Code Provider response code when present.
	Code *int `json:"code,omitempty"`

	// Msg Provider response message when present.
	Msg    *string       `json:"msg,omitempty"`
	Result *[]HomeRecord `json:"result,omitempty"`

	// Success Whether the operation succeeded, when present.
	Success *bool `json:"success,omitempty"`

	// T Provider response timestamp when present.
	T *int64 `json:"t,omitempty"`

	// Tid Provider trace identifier when present.
	Tid                  *string                `json:"tid,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// HomeRecord Home fields observed in the current implementation and example.
type HomeRecord struct {
	Background           *string                `json:"background,omitempty"`
	GeoName              *string                `json:"geoName,omitempty"`
	GroupId              *int                   `json:"groupId,omitempty"`
	Id                   *int64                 `json:"id,omitempty"`
	Lat                  *float64               `json:"lat,omitempty"`
	Lon                  *float64               `json:"lon,omitempty"`
	Name                 *string                `json:"name,omitempty"`
	OwnerId              *string                `json:"ownerId,omitempty"`
	Status               *bool                  `json:"status,omitempty"`
	Uid                  *string                `json:"uid,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// QueryHomeDevicesParams defines parameters for QueryHomeDevices.
type QueryHomeDevicesParams struct {
	// HomeId Home identifier used by home-device queries.
	HomeId *string `form:"homeId,omitempty" json:"homeId,omitempty"`

	// DeviceIds Comma-separated device IDs used by device-ID queries.
	DeviceIds *string `form:"deviceIds,omitempty" json:"deviceIds,omitempty"`
}

// Getter for additional properties for HomeDevicesEnvelope. Returns the specified
// element and whether it was found
func (a HomeDevicesEnvelope) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for HomeDevicesEnvelope
func (a *HomeDevicesEnvelope) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for HomeDevicesEnvelope to handle AdditionalProperties
func (a *HomeDevicesEnvelope) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["code"]; found {
		err = json.Unmarshal(raw, &a.Code)
		if err != nil {
			return fmt.Errorf("error reading 'code': %w", err)
		}
		delete(object, "code")
	}

	if raw, found := object["msg"]; found {
		err = json.Unmarshal(raw, &a.Msg)
		if err != nil {
			return fmt.Errorf("error reading 'msg': %w", err)
		}
		delete(object, "msg")
	}

	if raw, found := object["result"]; found {
		err = json.Unmarshal(raw, &a.Result)
		if err != nil {
			return fmt.Errorf("error reading 'result': %w", err)
		}
		delete(object, "result")
	}

	if raw, found := object["success"]; found {
		err = json.Unmarshal(raw, &a.Success)
		if err != nil {
			return fmt.Errorf("error reading 'success': %w", err)
		}
		delete(object, "success")
	}

	if raw, found := object["t"]; found {
		err = json.Unmarshal(raw, &a.T)
		if err != nil {
			return fmt.Errorf("error reading 't': %w", err)
		}
		delete(object, "t")
	}

	if raw, found := object["tid"]; found {
		err = json.Unmarshal(raw, &a.Tid)
		if err != nil {
			return fmt.Errorf("error reading 'tid': %w", err)
		}
		delete(object, "tid")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for HomeDevicesEnvelope to handle AdditionalProperties
func (a HomeDevicesEnvelope) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Code != nil {
		object["code"], err = json.Marshal(a.Code)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'code': %w", err)
		}
	}

	if a.Msg != nil {
		object["msg"], err = json.Marshal(a.Msg)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'msg': %w", err)
		}
	}

	if a.Result != nil {
		object["result"], err = json.Marshal(a.Result)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'result': %w", err)
		}
	}

	if a.Success != nil {
		object["success"], err = json.Marshal(a.Success)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'success': %w", err)
		}
	}

	if a.T != nil {
		object["t"], err = json.Marshal(a.T)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 't': %w", err)
		}
	}

	if a.Tid != nil {
		object["tid"], err = json.Marshal(a.Tid)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'tid': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for HomeListEnvelope. Returns the specified
// element and whether it was found
func (a HomeListEnvelope) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for HomeListEnvelope
func (a *HomeListEnvelope) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for HomeListEnvelope to handle AdditionalProperties
func (a *HomeListEnvelope) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["code"]; found {
		err = json.Unmarshal(raw, &a.Code)
		if err != nil {
			return fmt.Errorf("error reading 'code': %w", err)
		}
		delete(object, "code")
	}

	if raw, found := object["msg"]; found {
		err = json.Unmarshal(raw, &a.Msg)
		if err != nil {
			return fmt.Errorf("error reading 'msg': %w", err)
		}
		delete(object, "msg")
	}

	if raw, found := object["result"]; found {
		err = json.Unmarshal(raw, &a.Result)
		if err != nil {
			return fmt.Errorf("error reading 'result': %w", err)
		}
		delete(object, "result")
	}

	if raw, found := object["success"]; found {
		err = json.Unmarshal(raw, &a.Success)
		if err != nil {
			return fmt.Errorf("error reading 'success': %w", err)
		}
		delete(object, "success")
	}

	if raw, found := object["t"]; found {
		err = json.Unmarshal(raw, &a.T)
		if err != nil {
			return fmt.Errorf("error reading 't': %w", err)
		}
		delete(object, "t")
	}

	if raw, found := object["tid"]; found {
		err = json.Unmarshal(raw, &a.Tid)
		if err != nil {
			return fmt.Errorf("error reading 'tid': %w", err)
		}
		delete(object, "tid")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for HomeListEnvelope to handle AdditionalProperties
func (a HomeListEnvelope) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Code != nil {
		object["code"], err = json.Marshal(a.Code)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'code': %w", err)
		}
	}

	if a.Msg != nil {
		object["msg"], err = json.Marshal(a.Msg)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'msg': %w", err)
		}
	}

	if a.Result != nil {
		object["result"], err = json.Marshal(a.Result)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'result': %w", err)
		}
	}

	if a.Success != nil {
		object["success"], err = json.Marshal(a.Success)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'success': %w", err)
		}
	}

	if a.T != nil {
		object["t"], err = json.Marshal(a.T)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 't': %w", err)
		}
	}

	if a.Tid != nil {
		object["tid"], err = json.Marshal(a.Tid)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'tid': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for HomeRecord. Returns the specified
// element and whether it was found
func (a HomeRecord) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for HomeRecord
func (a *HomeRecord) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for HomeRecord to handle AdditionalProperties
func (a *HomeRecord) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["background"]; found {
		err = json.Unmarshal(raw, &a.Background)
		if err != nil {
			return fmt.Errorf("error reading 'background': %w", err)
		}
		delete(object, "background")
	}

	if raw, found := object["geoName"]; found {
		err = json.Unmarshal(raw, &a.GeoName)
		if err != nil {
			return fmt.Errorf("error reading 'geoName': %w", err)
		}
		delete(object, "geoName")
	}

	if raw, found := object["groupId"]; found {
		err = json.Unmarshal(raw, &a.GroupId)
		if err != nil {
			return fmt.Errorf("error reading 'groupId': %w", err)
		}
		delete(object, "groupId")
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if raw, found := object["lat"]; found {
		err = json.Unmarshal(raw, &a.Lat)
		if err != nil {
			return fmt.Errorf("error reading 'lat': %w", err)
		}
		delete(object, "lat")
	}

	if raw, found := object["lon"]; found {
		err = json.Unmarshal(raw, &a.Lon)
		if err != nil {
			return fmt.Errorf("error reading 'lon': %w", err)
		}
		delete(object, "lon")
	}

	if raw, found := object["name"]; found {
		err = json.Unmarshal(raw, &a.Name)
		if err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
		delete(object, "name")
	}

	if raw, found := object["ownerId"]; found {
		err = json.Unmarshal(raw, &a.OwnerId)
		if err != nil {
			return fmt.Errorf("error reading 'ownerId': %w", err)
		}
		delete(object, "ownerId")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if raw, found := object["uid"]; found {
		err = json.Unmarshal(raw, &a.Uid)
		if err != nil {
			return fmt.Errorf("error reading 'uid': %w", err)
		}
		delete(object, "uid")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for HomeRecord to handle AdditionalProperties
func (a HomeRecord) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Background != nil {
		object["background"], err = json.Marshal(a.Background)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'background': %w", err)
		}
	}

	if a.GeoName != nil {
		object["geoName"], err = json.Marshal(a.GeoName)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'geoName': %w", err)
		}
	}

	if a.GroupId != nil {
		object["groupId"], err = json.Marshal(a.GroupId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'groupId': %w", err)
		}
	}

	if a.Id != nil {
		object["id"], err = json.Marshal(a.Id)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'id': %w", err)
		}
	}

	if a.Lat != nil {
		object["lat"], err = json.Marshal(a.Lat)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'lat': %w", err)
		}
	}

	if a.Lon != nil {
		object["lon"], err = json.Marshal(a.Lon)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'lon': %w", err)
		}
	}

	if a.Name != nil {
		object["name"], err = json.Marshal(a.Name)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'name': %w", err)
		}
	}

	if a.OwnerId != nil {
		object["ownerId"], err = json.Marshal(a.OwnerId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'ownerId': %w", err)
		}
	}

	if a.Status != nil {
		object["status"], err = json.Marshal(a.Status)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'status': %w", err)
		}
	}

	if a.Uid != nil {
		object["uid"], err = json.Marshal(a.Uid)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'uid': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
