// Package tuyamodels provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package tuyamodels

import (
	"encoding/json"
	"fmt"
)

// MessageQueueConfigBody Link identifier payload used to request MQTT connection credentials.
type MessageQueueConfigBody struct {
	LinkId               string                 `json:"linkId"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// MessageQueueConfigEnvelope Tuya response envelope observed by the library. Unspecified envelope fields are retained.
type MessageQueueConfigEnvelope struct {
	// Code Provider response code when present.
	Code *int `json:"code,omitempty"`

	// Msg Provider response message when present.
	Msg *string `json:"msg,omitempty"`

	// Result MQTT connection fields consumed by the library. Treat credentials as secrets.
	Result *MessageQueueConfiguration `json:"result,omitempty"`

	// Success Whether the operation succeeded, when present.
	Success *bool `json:"success,omitempty"`

	// T Provider response timestamp when present.
	T *int64 `json:"t,omitempty"`

	// Tid Provider trace identifier when present.
	Tid                  *string                `json:"tid,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// MessageQueueConfiguration MQTT connection fields consumed by the library. Treat credentials as secrets.
type MessageQueueConfiguration struct {
	ClientId   *string `json:"clientId,omitempty"`
	ExpireTime *int64  `json:"expireTime,omitempty"`
	Password   *string `json:"password,omitempty"`

	// Topic MQTT topic groups returned by the private config route.
	Topic                *MessageQueueTopic     `json:"topic,omitempty"`
	Url                  *string                `json:"url,omitempty"`
	Username             *string                `json:"username,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// MessageQueueSubscription MQTT topic subscription data returned by the private config route.
type MessageQueueSubscription struct {
	Sub                  *string                `json:"sub,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// MessageQueueTopic MQTT topic groups returned by the private config route.
type MessageQueueTopic struct {
	// DevId MQTT topic subscription data returned by the private config route.
	DevId *MessageQueueSubscription `json:"devId,omitempty"`

	// OwnerId MQTT topic subscription data returned by the private config route.
	OwnerId              *MessageQueueSubscription `json:"ownerId,omitempty"`
	AdditionalProperties map[string]interface{}    `json:"-"`
}

// GetMessageQueueConfigJSONRequestBody defines body for GetMessageQueueConfig for application/json ContentType.
type GetMessageQueueConfigJSONRequestBody = MessageQueueConfigBody

// Getter for additional properties for MessageQueueConfigBody. Returns the specified
// element and whether it was found
func (a MessageQueueConfigBody) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for MessageQueueConfigBody
func (a *MessageQueueConfigBody) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for MessageQueueConfigBody to handle AdditionalProperties
func (a *MessageQueueConfigBody) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["linkId"]; found {
		err = json.Unmarshal(raw, &a.LinkId)
		if err != nil {
			return fmt.Errorf("error reading 'linkId': %w", err)
		}
		delete(object, "linkId")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for MessageQueueConfigBody to handle AdditionalProperties
func (a MessageQueueConfigBody) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["linkId"], err = json.Marshal(a.LinkId)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'linkId': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for MessageQueueConfigEnvelope. Returns the specified
// element and whether it was found
func (a MessageQueueConfigEnvelope) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for MessageQueueConfigEnvelope
func (a *MessageQueueConfigEnvelope) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for MessageQueueConfigEnvelope to handle AdditionalProperties
func (a *MessageQueueConfigEnvelope) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["code"]; found {
		err = json.Unmarshal(raw, &a.Code)
		if err != nil {
			return fmt.Errorf("error reading 'code': %w", err)
		}
		delete(object, "code")
	}

	if raw, found := object["msg"]; found {
		err = json.Unmarshal(raw, &a.Msg)
		if err != nil {
			return fmt.Errorf("error reading 'msg': %w", err)
		}
		delete(object, "msg")
	}

	if raw, found := object["result"]; found {
		err = json.Unmarshal(raw, &a.Result)
		if err != nil {
			return fmt.Errorf("error reading 'result': %w", err)
		}
		delete(object, "result")
	}

	if raw, found := object["success"]; found {
		err = json.Unmarshal(raw, &a.Success)
		if err != nil {
			return fmt.Errorf("error reading 'success': %w", err)
		}
		delete(object, "success")
	}

	if raw, found := object["t"]; found {
		err = json.Unmarshal(raw, &a.T)
		if err != nil {
			return fmt.Errorf("error reading 't': %w", err)
		}
		delete(object, "t")
	}

	if raw, found := object["tid"]; found {
		err = json.Unmarshal(raw, &a.Tid)
		if err != nil {
			return fmt.Errorf("error reading 'tid': %w", err)
		}
		delete(object, "tid")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for MessageQueueConfigEnvelope to handle AdditionalProperties
func (a MessageQueueConfigEnvelope) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Code != nil {
		object["code"], err = json.Marshal(a.Code)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'code': %w", err)
		}
	}

	if a.Msg != nil {
		object["msg"], err = json.Marshal(a.Msg)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'msg': %w", err)
		}
	}

	if a.Result != nil {
		object["result"], err = json.Marshal(a.Result)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'result': %w", err)
		}
	}

	if a.Success != nil {
		object["success"], err = json.Marshal(a.Success)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'success': %w", err)
		}
	}

	if a.T != nil {
		object["t"], err = json.Marshal(a.T)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 't': %w", err)
		}
	}

	if a.Tid != nil {
		object["tid"], err = json.Marshal(a.Tid)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'tid': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for MessageQueueConfiguration. Returns the specified
// element and whether it was found
func (a MessageQueueConfiguration) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for MessageQueueConfiguration
func (a *MessageQueueConfiguration) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for MessageQueueConfiguration to handle AdditionalProperties
func (a *MessageQueueConfiguration) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["clientId"]; found {
		err = json.Unmarshal(raw, &a.ClientId)
		if err != nil {
			return fmt.Errorf("error reading 'clientId': %w", err)
		}
		delete(object, "clientId")
	}

	if raw, found := object["expireTime"]; found {
		err = json.Unmarshal(raw, &a.ExpireTime)
		if err != nil {
			return fmt.Errorf("error reading 'expireTime': %w", err)
		}
		delete(object, "expireTime")
	}

	if raw, found := object["password"]; found {
		err = json.Unmarshal(raw, &a.Password)
		if err != nil {
			return fmt.Errorf("error reading 'password': %w", err)
		}
		delete(object, "password")
	}

	if raw, found := object["topic"]; found {
		err = json.Unmarshal(raw, &a.Topic)
		if err != nil {
			return fmt.Errorf("error reading 'topic': %w", err)
		}
		delete(object, "topic")
	}

	if raw, found := object["url"]; found {
		err = json.Unmarshal(raw, &a.Url)
		if err != nil {
			return fmt.Errorf("error reading 'url': %w", err)
		}
		delete(object, "url")
	}

	if raw, found := object["username"]; found {
		err = json.Unmarshal(raw, &a.Username)
		if err != nil {
			return fmt.Errorf("error reading 'username': %w", err)
		}
		delete(object, "username")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for MessageQueueConfiguration to handle AdditionalProperties
func (a MessageQueueConfiguration) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.ClientId != nil {
		object["clientId"], err = json.Marshal(a.ClientId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'clientId': %w", err)
		}
	}

	if a.ExpireTime != nil {
		object["expireTime"], err = json.Marshal(a.ExpireTime)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'expireTime': %w", err)
		}
	}

	if a.Password != nil {
		object["password"], err = json.Marshal(a.Password)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'password': %w", err)
		}
	}

	if a.Topic != nil {
		object["topic"], err = json.Marshal(a.Topic)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'topic': %w", err)
		}
	}

	if a.Url != nil {
		object["url"], err = json.Marshal(a.Url)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'url': %w", err)
		}
	}

	if a.Username != nil {
		object["username"], err = json.Marshal(a.Username)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'username': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for MessageQueueSubscription. Returns the specified
// element and whether it was found
func (a MessageQueueSubscription) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for MessageQueueSubscription
func (a *MessageQueueSubscription) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for MessageQueueSubscription to handle AdditionalProperties
func (a *MessageQueueSubscription) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["sub"]; found {
		err = json.Unmarshal(raw, &a.Sub)
		if err != nil {
			return fmt.Errorf("error reading 'sub': %w", err)
		}
		delete(object, "sub")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for MessageQueueSubscription to handle AdditionalProperties
func (a MessageQueueSubscription) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Sub != nil {
		object["sub"], err = json.Marshal(a.Sub)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'sub': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for MessageQueueTopic. Returns the specified
// element and whether it was found
func (a MessageQueueTopic) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for MessageQueueTopic
func (a *MessageQueueTopic) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for MessageQueueTopic to handle AdditionalProperties
func (a *MessageQueueTopic) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["devId"]; found {
		err = json.Unmarshal(raw, &a.DevId)
		if err != nil {
			return fmt.Errorf("error reading 'devId': %w", err)
		}
		delete(object, "devId")
	}

	if raw, found := object["ownerId"]; found {
		err = json.Unmarshal(raw, &a.OwnerId)
		if err != nil {
			return fmt.Errorf("error reading 'ownerId': %w", err)
		}
		delete(object, "ownerId")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for MessageQueueTopic to handle AdditionalProperties
func (a MessageQueueTopic) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.DevId != nil {
		object["devId"], err = json.Marshal(a.DevId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'devId': %w", err)
		}
	}

	if a.OwnerId != nil {
		object["ownerId"], err = json.Marshal(a.OwnerId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'ownerId': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
