// Code generated by tools/wireroutes from api/mqtt.asyncapi.yaml; DO NOT EDIT.
package tuyamodels

// MQTTChannel is a schema-defined subscription address template.
type MQTTChannel string

const (
	MQTTChannelDeviceStatus MQTTChannel = "{deviceTopic}/sta"
	MQTTChannelOwnerEvents  MQTTChannel = "{ownerTopic}"
)
