// Code generated by tools/wireroutes from api/openapi.yaml; DO NOT EDIT.
package tuyamodels

import "strings"

// Operation binds an HTTP method to its schema path.
type Operation struct {
	Method string
	Path   string
}

const (
	RouteAddDeviceUser             = "/v1.0/devices/%s/user"
	MethodAddDeviceUser            = "POST"
	RouteDeleteDevice              = "/v1.0/devices/%s"
	MethodDeleteDevice             = "DELETE"
	RouteDeleteDeviceUser          = "/v1.0/devices/%s/users/%s"
	MethodDeleteDeviceUser         = "DELETE"
	RouteGenerateLoginQRCode       = "/v1.0/m/life/home-assistant/qrcode/tokens"
	MethodGenerateLoginQRCode      = "POST"
	RouteGetDeviceDetails          = "/v1.0/devices/%s"
	MethodGetDeviceDetails         = "GET"
	RouteGetDeviceList             = "/v1.0/devices"
	MethodGetDeviceList            = "GET"
	RouteGetDeviceLogs             = "/v1.0/devices/%s/logs"
	MethodGetDeviceLogs            = "GET"
	RouteGetDeviceUser             = "/v1.0/devices/%s/users/%s"
	MethodGetDeviceUser            = "GET"
	RouteGetDevicesByUser          = "/v1.0/users/%s/devices"
	MethodGetDevicesByUser         = "GET"
	RouteGetFactoryInfos           = "/v1.0/devices/factory-infos"
	MethodGetFactoryInfos          = "GET"
	RouteGetMessageQueueConfig     = "/v1.0/m/life/ha/access/config"
	MethodGetMessageQueueConfig    = "POST"
	RouteGetSubDevices             = "/v1.0/devices/%s/sub-devices"
	MethodGetSubDevices            = "GET"
	RouteListDeviceUsers           = "/v1.0/devices/%s/users"
	MethodListDeviceUsers          = "GET"
	RouteListMultiOutletNames      = "/v1.0/devices/%s/multiple-names"
	MethodListMultiOutletNames     = "GET"
	RouteQueryDeviceSpecification  = "/v1.1/m/life/%s/specifications"
	MethodQueryDeviceSpecification = "GET"
	RouteQueryDeviceStatus         = "/v1.0/m/life/devices/%s/status"
	MethodQueryDeviceStatus        = "GET"
	RouteQueryHomeDevices          = "/v1.0/m/life/ha/home/devices"
	MethodQueryHomeDevices         = "GET"
	RouteQueryHomes                = "/v1.0/m/life/users/homes"
	MethodQueryHomes               = "GET"
	RouteRefreshAccessToken        = "/v1.0/m/token/%s"
	MethodRefreshAccessToken       = "GET"
	RouteResetDeviceFactory        = "/v1.0/devices/%s/reset-factory"
	MethodResetDeviceFactory       = "PUT"
	RouteSendDeviceCommands        = "/v1.1/m/thing/%s/commands"
	MethodSendDeviceCommands       = "POST"
	RouteStartRTCSession           = "/v1.0/m/life/ipc/%s/webrtc/session"
	MethodStartRTCSession          = "POST"
	RouteStopRTCSession            = "/v1.0/m/life/ipc/%s/webrtc/session/%s"
	MethodStopRTCSession           = "DELETE"
	RouteUpdateDeviceFunctionName  = "/v1.0/devices/%s/functions/%s"
	MethodUpdateDeviceFunctionName = "PUT"
	RouteUpdateDeviceName          = "/v1.0/devices/%s"
	MethodUpdateDeviceName         = "PUT"
	RouteUpdateDeviceUser          = "/v1.0/devices/%s/users/%s"
	MethodUpdateDeviceUser         = "PUT"
	RouteUpdateMultiOutletName     = "/v1.0/devices/%s/multiple-name"
	MethodUpdateMultiOutletName    = "PUT"
	RouteValidateLoginCode         = "/v1.0/m/life/home-assistant/qrcode/tokens/%s"
	MethodValidateLoginCode        = "GET"
)

func OperationAddDeviceUser() Operation {
	return Operation{Method: MethodAddDeviceUser, Path: RouteAddDeviceUser}
}
func OperationDeleteDevice() Operation {
	return Operation{Method: MethodDeleteDevice, Path: RouteDeleteDevice}
}
func OperationDeleteDeviceUser() Operation {
	return Operation{Method: MethodDeleteDeviceUser, Path: RouteDeleteDeviceUser}
}
func OperationGenerateLoginQRCode() Operation {
	return Operation{Method: MethodGenerateLoginQRCode, Path: RouteGenerateLoginQRCode}
}
func OperationGetDeviceDetails() Operation {
	return Operation{Method: MethodGetDeviceDetails, Path: RouteGetDeviceDetails}
}
func OperationGetDeviceList() Operation {
	return Operation{Method: MethodGetDeviceList, Path: RouteGetDeviceList}
}
func OperationGetDeviceLogs() Operation {
	return Operation{Method: MethodGetDeviceLogs, Path: RouteGetDeviceLogs}
}
func OperationGetDeviceUser() Operation {
	return Operation{Method: MethodGetDeviceUser, Path: RouteGetDeviceUser}
}
func OperationGetDevicesByUser() Operation {
	return Operation{Method: MethodGetDevicesByUser, Path: RouteGetDevicesByUser}
}
func OperationGetFactoryInfos() Operation {
	return Operation{Method: MethodGetFactoryInfos, Path: RouteGetFactoryInfos}
}
func OperationGetMessageQueueConfig() Operation {
	return Operation{Method: MethodGetMessageQueueConfig, Path: RouteGetMessageQueueConfig}
}
func OperationGetSubDevices() Operation {
	return Operation{Method: MethodGetSubDevices, Path: RouteGetSubDevices}
}
func OperationListDeviceUsers() Operation {
	return Operation{Method: MethodListDeviceUsers, Path: RouteListDeviceUsers}
}
func OperationListMultiOutletNames() Operation {
	return Operation{Method: MethodListMultiOutletNames, Path: RouteListMultiOutletNames}
}
func OperationQueryDeviceSpecification() Operation {
	return Operation{Method: MethodQueryDeviceSpecification, Path: RouteQueryDeviceSpecification}
}
func OperationQueryDeviceStatus() Operation {
	return Operation{Method: MethodQueryDeviceStatus, Path: RouteQueryDeviceStatus}
}
func OperationQueryHomeDevices() Operation {
	return Operation{Method: MethodQueryHomeDevices, Path: RouteQueryHomeDevices}
}
func OperationQueryHomes() Operation {
	return Operation{Method: MethodQueryHomes, Path: RouteQueryHomes}
}
func OperationRefreshAccessToken() Operation {
	return Operation{Method: MethodRefreshAccessToken, Path: RouteRefreshAccessToken}
}
func OperationResetDeviceFactory() Operation {
	return Operation{Method: MethodResetDeviceFactory, Path: RouteResetDeviceFactory}
}
func OperationSendDeviceCommands() Operation {
	return Operation{Method: MethodSendDeviceCommands, Path: RouteSendDeviceCommands}
}
func OperationStartRTCSession() Operation {
	return Operation{Method: MethodStartRTCSession, Path: RouteStartRTCSession}
}
func OperationStopRTCSession() Operation {
	return Operation{Method: MethodStopRTCSession, Path: RouteStopRTCSession}
}
func OperationUpdateDeviceFunctionName() Operation {
	return Operation{Method: MethodUpdateDeviceFunctionName, Path: RouteUpdateDeviceFunctionName}
}
func OperationUpdateDeviceName() Operation {
	return Operation{Method: MethodUpdateDeviceName, Path: RouteUpdateDeviceName}
}
func OperationUpdateDeviceUser() Operation {
	return Operation{Method: MethodUpdateDeviceUser, Path: RouteUpdateDeviceUser}
}
func OperationUpdateMultiOutletName() Operation {
	return Operation{Method: MethodUpdateMultiOutletName, Path: RouteUpdateMultiOutletName}
}
func OperationValidateLoginCode() Operation {
	return Operation{Method: MethodValidateLoginCode, Path: RouteValidateLoginCode}
}

var knownOperations = []Operation{
	OperationAddDeviceUser(),
	OperationDeleteDevice(),
	OperationDeleteDeviceUser(),
	OperationGenerateLoginQRCode(),
	OperationGetDeviceDetails(),
	OperationGetDeviceList(),
	OperationGetDeviceLogs(),
	OperationGetDeviceUser(),
	OperationGetDevicesByUser(),
	OperationGetFactoryInfos(),
	OperationGetMessageQueueConfig(),
	OperationGetSubDevices(),
	OperationListDeviceUsers(),
	OperationListMultiOutletNames(),
	OperationQueryDeviceSpecification(),
	OperationQueryDeviceStatus(),
	OperationQueryHomeDevices(),
	OperationQueryHomes(),
	OperationRefreshAccessToken(),
	OperationResetDeviceFactory(),
	OperationSendDeviceCommands(),
	OperationStartRTCSession(),
	OperationStopRTCSession(),
	OperationUpdateDeviceFunctionName(),
	OperationUpdateDeviceName(),
	OperationUpdateDeviceUser(),
	OperationUpdateMultiOutletName(),
	OperationValidateLoginCode(),
}

// IsKnownOperation accepts only a method and path defined in the OpenAPI inventory.
func IsKnownOperation(method, path string) bool {
	if strings.ContainsAny(path, "?#") {
		return false
	}
	for _, operation := range knownOperations {
		if method == operation.Method && matchesOperationPath(operation.Path, path) {
			return true
		}
	}
	return false
}

func matchesOperationPath(template, path string) bool {
	templateParts := strings.Split(template, "/")
	pathParts := strings.Split(path, "/")
	if len(templateParts) != len(pathParts) {
		return false
	}
	for index, part := range templateParts {
		if part == "%s" {
			if pathParts[index] == "" {
				return false
			}
			continue
		}
		if part != pathParts[index] {
			return false
		}
	}
	return true
}
