// Package tuyamodels provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package tuyamodels

import (
	"encoding/json"
	"fmt"
)

// Defines values for RTCOfferBodyType.
const (
	Offer RTCOfferBodyType = "offer"
)

// Valid indicates whether the value is a known member of the RTCOfferBodyType enum.
func (e RTCOfferBodyType) Valid() bool {
	switch e {
	case Offer:
		return true
	default:
		return false
	}
}

// RTCOfferBody WebRTC offer payload sent to Tuya signaling.
type RTCOfferBody struct {
	Sdp                  string                 `json:"sdp"`
	Type                 RTCOfferBodyType       `json:"type"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// RTCOfferBodyType defines model for RTCOfferBody.Type.
type RTCOfferBodyType string

// RTCSessionEnvelope Tuya response envelope observed by the library. Unspecified envelope fields are retained.
type RTCSessionEnvelope struct {
	// Code Provider response code when present.
	Code *int `json:"code,omitempty"`

	// Msg Provider response message when present.
	Msg *string `json:"msg,omitempty"`

	// Result WebRTC signaling response fields consumed by the library.
	Result *RTCSessionResult `json:"result,omitempty"`

	// Success Whether the operation succeeded, when present.
	Success *bool `json:"success,omitempty"`

	// T Provider response timestamp when present.
	T *int64 `json:"t,omitempty"`

	// Tid Provider trace identifier when present.
	Tid                  *string                `json:"tid,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// RTCSessionResult WebRTC signaling response fields consumed by the library.
type RTCSessionResult struct {
	Sdp                  *string                `json:"sdp,omitempty"`
	SessionId            *string                `json:"session_id,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// StartRTCSessionJSONRequestBody defines body for StartRTCSession for application/json ContentType.
type StartRTCSessionJSONRequestBody = RTCOfferBody

// Getter for additional properties for RTCOfferBody. Returns the specified
// element and whether it was found
func (a RTCOfferBody) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for RTCOfferBody
func (a *RTCOfferBody) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for RTCOfferBody to handle AdditionalProperties
func (a *RTCOfferBody) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["sdp"]; found {
		err = json.Unmarshal(raw, &a.Sdp)
		if err != nil {
			return fmt.Errorf("error reading 'sdp': %w", err)
		}
		delete(object, "sdp")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for RTCOfferBody to handle AdditionalProperties
func (a RTCOfferBody) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["sdp"], err = json.Marshal(a.Sdp)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'sdp': %w", err)
	}

	object["type"], err = json.Marshal(a.Type)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'type': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for RTCSessionEnvelope. Returns the specified
// element and whether it was found
func (a RTCSessionEnvelope) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for RTCSessionEnvelope
func (a *RTCSessionEnvelope) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for RTCSessionEnvelope to handle AdditionalProperties
func (a *RTCSessionEnvelope) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["code"]; found {
		err = json.Unmarshal(raw, &a.Code)
		if err != nil {
			return fmt.Errorf("error reading 'code': %w", err)
		}
		delete(object, "code")
	}

	if raw, found := object["msg"]; found {
		err = json.Unmarshal(raw, &a.Msg)
		if err != nil {
			return fmt.Errorf("error reading 'msg': %w", err)
		}
		delete(object, "msg")
	}

	if raw, found := object["result"]; found {
		err = json.Unmarshal(raw, &a.Result)
		if err != nil {
			return fmt.Errorf("error reading 'result': %w", err)
		}
		delete(object, "result")
	}

	if raw, found := object["success"]; found {
		err = json.Unmarshal(raw, &a.Success)
		if err != nil {
			return fmt.Errorf("error reading 'success': %w", err)
		}
		delete(object, "success")
	}

	if raw, found := object["t"]; found {
		err = json.Unmarshal(raw, &a.T)
		if err != nil {
			return fmt.Errorf("error reading 't': %w", err)
		}
		delete(object, "t")
	}

	if raw, found := object["tid"]; found {
		err = json.Unmarshal(raw, &a.Tid)
		if err != nil {
			return fmt.Errorf("error reading 'tid': %w", err)
		}
		delete(object, "tid")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for RTCSessionEnvelope to handle AdditionalProperties
func (a RTCSessionEnvelope) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Code != nil {
		object["code"], err = json.Marshal(a.Code)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'code': %w", err)
		}
	}

	if a.Msg != nil {
		object["msg"], err = json.Marshal(a.Msg)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'msg': %w", err)
		}
	}

	if a.Result != nil {
		object["result"], err = json.Marshal(a.Result)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'result': %w", err)
		}
	}

	if a.Success != nil {
		object["success"], err = json.Marshal(a.Success)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'success': %w", err)
		}
	}

	if a.T != nil {
		object["t"], err = json.Marshal(a.T)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 't': %w", err)
		}
	}

	if a.Tid != nil {
		object["tid"], err = json.Marshal(a.Tid)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'tid': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for RTCSessionResult. Returns the specified
// element and whether it was found
func (a RTCSessionResult) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for RTCSessionResult
func (a *RTCSessionResult) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for RTCSessionResult to handle AdditionalProperties
func (a *RTCSessionResult) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["sdp"]; found {
		err = json.Unmarshal(raw, &a.Sdp)
		if err != nil {
			return fmt.Errorf("error reading 'sdp': %w", err)
		}
		delete(object, "sdp")
	}

	if raw, found := object["session_id"]; found {
		err = json.Unmarshal(raw, &a.SessionId)
		if err != nil {
			return fmt.Errorf("error reading 'session_id': %w", err)
		}
		delete(object, "session_id")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for RTCSessionResult to handle AdditionalProperties
func (a RTCSessionResult) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Sdp != nil {
		object["sdp"], err = json.Marshal(a.Sdp)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'sdp': %w", err)
		}
	}

	if a.SessionId != nil {
		object["session_id"], err = json.Marshal(a.SessionId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'session_id': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
