// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.

package tuya

// Defines values for LockState.
const (
	LockStateLocked   LockState = "locked"
	LockStateUnlocked LockState = "unlocked"
)

// Valid indicates whether the value is a known member of the LockState enum.
func (e LockState) Valid() bool {
	switch e {
	case LockStateLocked:
		return true
	case LockStateUnlocked:
		return true
	default:
		return false
	}
}

// Defines values for PowerState.
const (
	PowerStateOff PowerState = "off"
	PowerStateOn  PowerState = "on"
)

// Valid indicates whether the value is a known member of the PowerState enum.
func (e PowerState) Valid() bool {
	switch e {
	case PowerStateOff:
		return true
	case PowerStateOn:
		return true
	default:
		return false
	}
}

// Defines values for StreamingState.
const (
	StreamingStateIdle      StreamingState = "idle"
	StreamingStateStreaming StreamingState = "streaming"
)

// Valid indicates whether the value is a known member of the StreamingState enum.
func (e StreamingState) Valid() bool {
	switch e {
	case StreamingStateIdle:
		return true
	case StreamingStateStreaming:
		return true
	default:
		return false
	}
}

// BrightnessCapability defines model for BrightnessCapability.
type BrightnessCapability struct {
	Level int `json:"level"`
}

// CameraCapability defines model for CameraCapability.
type CameraCapability struct {
	StreamingState StreamingState `json:"streamingState"`
}

// CapabilityType Stable semantic capability identifiers exposed by this SDK.
type CapabilityType = string

// ColorCapability defines model for ColorCapability.
type ColorCapability struct {
	Hue        int `json:"hue"`
	Saturation int `json:"saturation"`
	Value      int `json:"value"`
}

// ColorTemperatureCapability defines model for ColorTemperatureCapability.
type ColorTemperatureCapability struct {
	Mireds int `json:"mireds"`
}

// ContactSensorCapability defines model for ContactSensorCapability.
type ContactSensorCapability struct {
	IsOpen bool `json:"isOpen"`
}

// DeviceDeleteEvent defines model for DeviceDeleteEvent.
type DeviceDeleteEvent struct {
	DeviceID   string `json:"devId"`
	ProductKey string `json:"productKey"`
	UID        string `json:"uid"`
}

// DeviceManagementEvent Public projection of a Tuya device-management event.
type DeviceManagementEvent struct {
	BizCode    string                 `json:"bizCode"`
	BizData    map[string]interface{} `json:"bizData"`
	DeviceID   string                 `json:"devId"`
	ProductKey string                 `json:"productKey"`
}

// DeviceNameUpdateEvent defines model for DeviceNameUpdateEvent.
type DeviceNameUpdateEvent struct {
	DeviceID   string `json:"devId"`
	NewName    string `json:"name"`
	ProductKey string `json:"productKey"`
}

// DeviceOfflineEvent defines model for DeviceOfflineEvent.
type DeviceOfflineEvent struct {
	DeviceID   string `json:"devId"`
	ProductKey string `json:"productKey"`
	Time       int64  `json:"time"`
}

// DeviceOnlineEvent defines model for DeviceOnlineEvent.
type DeviceOnlineEvent struct {
	DeviceID   string `json:"devId"`
	ProductKey string `json:"productKey"`
	Time       int64  `json:"time"`
}

// DeviceStateChangeEvent Public projection of a Tuya device status-change event.
type DeviceStateChangeEvent struct {
	DataID     string               `json:"dataId"`
	DeviceID   string               `json:"devId"`
	ProductKey string               `json:"productKey"`
	Status     []DeviceStatusChange `json:"status"`
}

// DeviceStatusChange Public projection of one status entry in a Tuya device report.
type DeviceStatusChange struct {
	Code      string      `json:"code"`
	Timestamp int64       `json:"t"`
	Value     interface{} `json:"value"`
}

// FanSpeedCapability defines model for FanSpeedCapability.
type FanSpeedCapability struct {
	Speed int `json:"speed"`
}

// HumiditySensorCapability defines model for HumiditySensorCapability.
type HumiditySensorCapability struct {
	Humidity int `json:"humidity"`
}

// LockCapability defines model for LockCapability.
type LockCapability struct {
	State LockState `json:"state"`
}

// LockState defines model for LockState.
type LockState string

// PowerCapability defines model for PowerCapability.
type PowerCapability struct {
	State PowerState `json:"state"`
}

// PowerState defines model for PowerState.
type PowerState string

// StandardizedDeviceStateEvent defines model for StandardizedDeviceStateEvent.
type StandardizedDeviceStateEvent struct {
	Capabilities []Capability `json:"capabilities"`
	Category     string       `json:"category"`
	DeviceID     string       `json:"deviceId"`
	ProductKey   string       `json:"productKey"`
	Timestamp    int64        `json:"timestamp"`
}

// StreamingState defines model for StreamingState.
type StreamingState string

// TemperatureSensorCapability defines model for TemperatureSensorCapability.
type TemperatureSensorCapability struct {
	Temperature float64 `json:"temperature"`
}

// WindowCoveringCapability defines model for WindowCoveringCapability.
type WindowCoveringCapability struct {
	Position int `json:"position"`
}
