// Code generated by tools/publicmodels from api/public-projections.yaml; DO NOT EDIT.

package tuya

const (
	ProjectionPropertyBrightnessCapabilityLevel = "level"
)

const (
	ProjectionPropertyCameraCapabilityStreamingState = "streamingState"
)

const (
	CapabilityTypePower = "power"
	CapabilityTypeBrightness = "brightness"
	CapabilityTypeColor = "color"
	CapabilityTypeColorTemperature = "color-temperature"
	CapabilityTypeTemperatureSensor = "temperature-sensor"
	CapabilityTypeHumiditySensor = "humidity-sensor"
	CapabilityTypeFanSpeed = "fan-speed"
	CapabilityTypeLock = "lock"
	CapabilityTypeContactSensor = "contact-sensor"
	CapabilityTypeWindowCovering = "window-covering"
	CapabilityTypeCamera = "camera"
	CapabilityTypeRTCSession = "rtc-session"
)

const (
	ProjectionPropertyColorCapabilityHue = "hue"
	ProjectionPropertyColorCapabilitySaturation = "saturation"
	ProjectionPropertyColorCapabilityValue = "value"
)

const (
	ProjectionPropertyColorTemperatureCapabilityMireds = "mireds"
)

const (
	ProjectionPropertyContactSensorCapabilityIsOpen = "isOpen"
)

const (
	ContactSensorTextValueTrue = "true"
	ContactSensorTextValueOpen = "open"
	ContactSensorTextValueFalse = "false"
	ContactSensorTextValueClosed = "closed"
)

const (
	ProjectionPropertyDeviceDeleteEventDevId = "devId"
	ProjectionPropertyDeviceDeleteEventProductKey = "productKey"
	ProjectionPropertyDeviceDeleteEventUid = "uid"
)

const (
	ProjectionPropertyDeviceManagementEventBizCode = "bizCode"
	ProjectionPropertyDeviceManagementEventBizData = "bizData"
	ProjectionPropertyDeviceManagementEventDevId = "devId"
	ProjectionPropertyDeviceManagementEventProductKey = "productKey"
)

const (
	ProjectionPropertyDeviceNameUpdateEventDevId = "devId"
	ProjectionPropertyDeviceNameUpdateEventName = "name"
	ProjectionPropertyDeviceNameUpdateEventProductKey = "productKey"
)

const (
	ProjectionPropertyDeviceOfflineEventDevId = "devId"
	ProjectionPropertyDeviceOfflineEventProductKey = "productKey"
	ProjectionPropertyDeviceOfflineEventTime = "time"
)

const (
	ProjectionPropertyDeviceOnlineEventDevId = "devId"
	ProjectionPropertyDeviceOnlineEventProductKey = "productKey"
	ProjectionPropertyDeviceOnlineEventTime = "time"
)

const (
	ProjectionPropertyDeviceStateChangeEventDataId = "dataId"
	ProjectionPropertyDeviceStateChangeEventDevId = "devId"
	ProjectionPropertyDeviceStateChangeEventProductKey = "productKey"
	ProjectionPropertyDeviceStateChangeEventStatus = "status"
)

const (
	ProjectionPropertyDeviceStatusChangeCode = "code"
	ProjectionPropertyDeviceStatusChangeT = "t"
	ProjectionPropertyDeviceStatusChangeValue = "value"
)

const (
	ProjectionPropertyFanSpeedCapabilitySpeed = "speed"
)

const (
	ProjectionPropertyHumiditySensorCapabilityHumidity = "humidity"
)

const (
	ProjectionPropertyLockCapabilityState = "state"
)

const (
	ProjectionPropertyPowerCapabilityState = "state"
)

type RTCSessionCapability struct{}

const (
	SDKEventTypeDeviceStateChange = "device_state_change"
	SDKEventTypeDeviceManagementPrefix = "device_management_"
	SDKEventTypeDeviceOnline = "device_online"
	SDKEventTypeDeviceOffline = "device_offline"
	SDKEventTypeDeviceNameUpdate = "device_name_update"
	SDKEventTypeDeviceDelete = "device_delete"
)

const (
	ProjectionPropertyStandardizedDeviceStateEventCapabilities = "capabilities"
	ProjectionPropertyStandardizedDeviceStateEventCategory = "category"
	ProjectionPropertyStandardizedDeviceStateEventDeviceId = "deviceId"
	ProjectionPropertyStandardizedDeviceStateEventProductKey = "productKey"
	ProjectionPropertyStandardizedDeviceStateEventTimestamp = "timestamp"
)

const (
	ProjectionPropertyTemperatureSensorCapabilityTemperature = "temperature"
)

const (
	ProjectionPropertyWindowCoveringCapabilityPosition = "position"
)
