// Command publicmodels checks and generates SDK-owned semantic projections.
package main

import (
	"bytes"
	"context"
	"errors"
	"flag"
	"fmt"
	"go/format"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"sort"
	"strconv"
	"strings"
	"unicode"

	"gopkg.in/yaml.v3"
)

const (
	schemaPath                  = "api/public-projections.yaml"
	configPath                  = "pkg/tuya/public-projections.config.yaml"
	modelOutputPath             = "pkg/tuya/public_projections.gen.go"
	constOutputPath             = "pkg/tuya/public_values.gen.go"
	publicValuesGeneratedHeader = "// Code generated by tools/publicmodels from api/public-projections.yaml; DO NOT EDIT."
	importsTemplatePath         = "tools/publicmodels/templates/imports.tmpl"
	generatorVersion            = "v2.8.0"
	filePermissions             = 0o644
)

var (
	errInvalidProjectionSchema = errors.New("invalid public projection schema")
	errGeneratedDrift          = errors.New("generated public projections differ from schema")
	errModeSelection           = errors.New("select exactly one of -check or -generate")
)

func main() {
	check := flag.Bool("check", false, "check public projection model generation")
	generate := flag.Bool("generate", false, "generate public projection models")

	flag.Parse()

	if *check == *generate {
		fatal(errModeSelection)
	}

	err := run(*generate)
	if err != nil {
		fatal(err)
	}
}

func run(generate bool) error {
	schema, err := readDocument(schemaPath)
	if err != nil {
		return err
	}

	config, err := readDocument(configPath)
	if err != nil {
		return err
	}

	err = validateConfig(config)
	if err != nil {
		return err
	}

	constants, err := generateUntypedConstants(schema)
	if err != nil {
		return err
	}

	if generate {
		err = runGenerator(configPath, schemaPath)
		if err != nil {
			return err
		}

		return writeFile(constOutputPath, constants)
	}

	err = checkGeneratedModel()
	if err != nil {
		return err
	}

	return checkFile(constOutputPath, constants)
}

func readDocument(path string) (map[string]any, error) {
	// #nosec G304 -- paths are fixed checked-in schema and generator configuration.
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", path, err)
	}

	var document map[string]any

	err = yaml.Unmarshal(data, &document)
	if err != nil {
		return nil, fmt.Errorf("decode %s: %w", path, err)
	}

	return document, nil
}

func validateConfig(config map[string]any) error {
	generator, validGenerator := config["generate"].(map[string]any)
	if !validGenerator || !reflect.DeepEqual(generator, map[string]any{"models": true}) {
		return fmt.Errorf("public projection generator must only generate models: %w", errInvalidProjectionSchema)
	}

	if config["package"] != "tuya" || config["output"] != modelOutputPath {
		return fmt.Errorf("public projection generator package/output mismatch: %w", errInvalidProjectionSchema)
	}

	outputOptions, validOptions := config["output-options"].(map[string]any)
	if !validOptions || !validPointerOptions(outputOptions) {
		return fmt.Errorf("public projection pointer configuration changed: %w", errInvalidProjectionSchema)
	}

	return nil
}

func validPointerOptions(options map[string]any) bool {
	excludedSchemas, validExclusions := options["exclude-schemas"].([]any)

	expectedExclusions := []any{
		"CapabilityNormalization", "ContactSensorTextValue", "RTCSessionCapability", "SDKEventType",
	}
	if !validExclusions || !reflect.DeepEqual(excludedSchemas, expectedExclusions) {
		return false
	}

	userTemplates, validTemplates := options["user-templates"].(map[string]any)
	if !validTemplates || !reflect.DeepEqual(userTemplates, map[string]any{"imports.tmpl": importsTemplatePath}) {
		return false
	}

	return options["skip-prune"] == true &&
		options["prefer-skip-optional-pointer"] == true &&
		options["prefer-skip-optional-pointer-on-container-types"] == true
}

func generateUntypedConstants(document map[string]any) ([]byte, error) {
	schemas, err := projectionSchemas(document)
	if err != nil {
		return nil, err
	}

	names := sortedProjectionSchemaNames(schemas)

	var output strings.Builder

	output.WriteString(publicValuesGeneratedHeader + "\n\n")
	output.WriteString("package tuya\n\n")

	seenNames := make(map[string]bool)
	generatedAny := false

	for _, schemaName := range names {
		schema, validSchema := schemas[schemaName].(map[string]any)
		if !validSchema {
			continue
		}

		generated, writeErr := writeUntypedSchema(&output, schemaName, schema, seenNames)
		if writeErr != nil {
			return nil, writeErr
		}

		generatedAny = generatedAny || generated
	}

	if !generatedAny {
		return nil, fmt.Errorf("no schemas opted in to untyped constant generation: %w", errInvalidProjectionSchema)
	}

	formatted, err := format.Source([]byte(output.String()))
	if err != nil {
		return nil, fmt.Errorf("format generated public values: %w", err)
	}

	return formatted, nil
}

func projectionSchemas(document map[string]any) (map[string]any, error) {
	components, validComponents := document["components"].(map[string]any)
	if !validComponents {
		return nil, fmt.Errorf("components are absent: %w", errInvalidProjectionSchema)
	}

	schemas, validSchemas := components["schemas"].(map[string]any)
	if !validSchemas || len(schemas) == 0 {
		return nil, fmt.Errorf("schemas are absent: %w", errInvalidProjectionSchema)
	}

	return schemas, nil
}

func sortedProjectionSchemaNames(schemas map[string]any) []string {
	names := make([]string, 0, len(schemas))
	for name := range schemas {
		names = append(names, name)
	}

	sort.Strings(names)

	return names
}

func writeUntypedSchema(output *strings.Builder, schemaName string, schema map[string]any, seenNames map[string]bool) (bool, error) {
	generated := false

	var err error

	if schema["x-go-tuya-generate-empty-struct"] == true {
		err = writeEmptyProjectionMarker(output, schemaName, schema)
		if err != nil {
			return false, err
		}

		return true, nil
	}

	if schema["x-go-tuya-generate-untyped-constants"] == true {
		err = writeProjectionEnum(output, schemaName, schema, seenNames)
		if err != nil {
			return false, err
		}

		generated = true
	}

	numericConstants, err := writeProjectionNumericConstants(output, schemaName, schema, seenNames)
	if err != nil {
		return false, err
	}

	generated = generated || numericConstants

	err = writeProjectionProperties(output, schemaName, schema, seenNames)
	if err != nil {
		return false, err
	}

	properties, hasProperties := schema["properties"].(map[string]any)

	return generated || (hasProperties && len(properties) > 0), nil
}

func writeProjectionNumericConstants(output *strings.Builder, schemaName string, schema map[string]any, seenNames map[string]bool) (bool, error) {
	rawConstants, hasConstants := schema["x-go-tuya-numeric-constants"]
	if !hasConstants {
		return false, nil
	}

	constants, validConstants := rawConstants.(map[string]any)

	properties, hasProperties := schema["properties"].(map[string]any)

	if !validNumericConstantSchema(schema, constants, validConstants, properties, hasProperties) {
		return false, fmt.Errorf("schema %q has invalid numeric constants: %w", schemaName, errInvalidProjectionSchema)
	}

	names := make([]string, 0, len(constants))
	for name := range constants {
		names = append(names, name)
	}

	sort.Strings(names)

	values := make(map[string]string, len(constants))

	for _, name := range names {
		value, err := projectionNumericConstant(schemaName, name, constants[name], seenNames)
		if err != nil {
			return false, err
		}

		seenNames[name] = true
		values[name] = value
	}

	output.WriteString("const (\n")

	for _, name := range names {
		fmt.Fprintf(output, "\t%s = %s\n", name, values[name])
	}

	output.WriteString(")\n\n")

	return true, nil
}

func validNumericConstantSchema(schema map[string]any, constants map[string]any, validConstants bool, properties map[string]any, hasProperties bool) bool {
	return schema["type"] == "object" && validConstants && len(constants) > 0 && (!hasProperties || len(properties) == 0)
}

func projectionNumericConstant(schemaName, name string, rawValue any, seenNames map[string]bool) (string, error) {
	value, validValue := projectionInteger(rawValue)
	if !token.IsIdentifier(name) || name == "_" || name == "" || !unicode.IsUpper([]rune(name)[0]) || seenNames[name] || !validValue {
		return "", fmt.Errorf("schema %q has invalid or duplicate numeric constant %q: %w", schemaName, name, errInvalidProjectionSchema)
	}

	return value, nil
}

func projectionInteger(value any) (string, bool) {
	switch value := value.(type) {
	case int:
		return strconv.Itoa(value), true
	case int64:
		return strconv.FormatInt(value, 10), true
	case uint64:
		return strconv.FormatUint(value, 10), true
	default:
		return "", false
	}
}

func writeEmptyProjectionMarker(output *strings.Builder, schemaName string, schema map[string]any) error {
	properties, hasProperties := schema["properties"].(map[string]any)
	if schema["type"] != "object" || (hasProperties && len(properties) != 0) || !token.IsIdentifier(schemaName) {
		return fmt.Errorf("schema %q cannot generate an empty public marker: %w", schemaName, errInvalidProjectionSchema)
	}

	fmt.Fprintf(output, "type %s struct{}\n\n", schemaName)

	return nil
}

func writeProjectionEnum(output *strings.Builder, schemaName string, schema map[string]any, seenNames map[string]bool) error {
	values, variableNames, err := projectionEnumValues(schemaName, schema)
	if err != nil {
		return err
	}

	output.WriteString("const (\n")

	seenValues := make(map[string]bool)

	for index, rawValue := range values {
		value, validValue := rawValue.(string)

		name, validName := variableNames[index].(string)

		if !validValue || !validName || !token.IsIdentifier(name) || name == "_" || seenNames[name] || seenValues[value] {
			return fmt.Errorf("schema %q enum entry %d is invalid or duplicated: %w", schemaName, index, errInvalidProjectionSchema)
		}

		seenNames[name] = true
		seenValues[value] = true

		fmt.Fprintf(output, "\t%s = %q\n", name, value)
	}

	output.WriteString(")\n\n")

	return nil
}

func projectionEnumValues(schemaName string, schema map[string]any) ([]any, []any, error) {
	values, validValues := schema["enum"].([]any)
	variableNames, validNames := schema["x-enum-varnames"].([]any)

	if schema["type"] != "string" || !validValues || !validNames || len(values) == 0 || len(values) != len(variableNames) {
		return nil, nil, fmt.Errorf("schema %q must have paired string enum values and x-enum-varnames: %w", schemaName, errInvalidProjectionSchema)
	}

	return values, variableNames, nil
}

func writeProjectionProperties(output *strings.Builder, schemaName string, schema map[string]any, seenNames map[string]bool) error {
	properties, hasProperties := schema["properties"].(map[string]any)
	if !hasProperties || len(properties) == 0 {
		return nil
	}

	propertyNames := make([]string, 0, len(properties))
	for propertyName := range properties {
		propertyNames = append(propertyNames, propertyName)
	}

	sort.Strings(propertyNames)
	output.WriteString("const (\n")

	for _, propertyName := range propertyNames {
		name := "ProjectionProperty" + schemaName + propertyIdentifier(propertyName)
		if !token.IsIdentifier(name) || seenNames[name] {
			return fmt.Errorf("schema %q property %q has invalid or duplicate constant name %q: %w", schemaName, propertyName, name, errInvalidProjectionSchema)
		}

		seenNames[name] = true

		fmt.Fprintf(output, "\t%s = %q\n", name, propertyName)
	}

	output.WriteString(")\n\n")

	return nil
}

func propertyIdentifier(name string) string {
	var output strings.Builder

	upperNext := true

	for _, character := range name {
		if !unicode.IsLetter(character) && !unicode.IsDigit(character) {
			upperNext = true

			continue
		}

		if upperNext {
			output.WriteRune(unicode.ToUpper(character))

			upperNext = false

			continue
		}

		output.WriteRune(character)
	}

	return output.String()
}

func checkGeneratedModel() error {
	directory, err := os.MkdirTemp("", "go-tuya-public-models-")
	if err != nil {
		return fmt.Errorf("create public model check directory: %w", err)
	}

	defer func() {
		_ = os.RemoveAll(directory)
	}()

	temporaryOutput := filepath.Join(directory, "public_projections.gen.go")
	temporaryConfig := filepath.Join(directory, "config.yaml")
	config := map[string]any{
		"package": "tuya",
		"generate": map[string]any{
			"models": true,
		},
		"output": temporaryOutput,
		"output-options": map[string]any{
			"exclude-schemas":              []any{"CapabilityNormalization", "ContactSensorTextValue", "RTCSessionCapability", "SDKEventType"},
			"skip-prune":                   true,
			"prefer-skip-optional-pointer": true,
			"prefer-skip-optional-pointer-on-container-types": true,
			"user-templates": map[string]any{
				"imports.tmpl": importsTemplatePath,
			},
		},
	}

	configuration, err := yaml.Marshal(config)
	if err != nil {
		return fmt.Errorf("encode temporary public model config: %w", err)
	}

	// #nosec G306 -- the temporary config only contains repository-derived generator options.
	err = os.WriteFile(temporaryConfig, configuration, filePermissions)
	if err != nil {
		return fmt.Errorf("write temporary public model config: %w", err)
	}

	err = runGenerator(temporaryConfig, schemaPath)
	if err != nil {
		return err
	}

	// #nosec G304 -- output path is generated from a fresh temporary directory.
	expected, err := os.ReadFile(temporaryOutput)
	if err != nil {
		return fmt.Errorf("read generated public model output: %w", err)
	}

	// #nosec G304 -- target is a fixed generated source path.
	current, err := os.ReadFile(modelOutputPath)
	if err != nil {
		return fmt.Errorf("read generated public model source: %w", err)
	}

	if !bytes.Equal(current, expected) {
		return fmt.Errorf("%s: %w; run make generate-wire", modelOutputPath, errGeneratedDrift)
	}

	return nil
}

func runGenerator(config, schema string) error {
	// #nosec G204 -- command is the pinned generator with repository-local config/schema paths.
	command := exec.CommandContext(
		context.Background(),
		"go",
		"run",
		"github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@"+generatorVersion,
		"-config",
		config,
		schema,
	)
	command.Stdout = os.Stdout
	command.Stderr = os.Stderr

	err := command.Run()
	if err != nil {
		return fmt.Errorf("run pinned public model generator: %w", err)
	}

	return nil
}

func writeFile(path string, content []byte) error {
	// #nosec G306 -- generated Go source is public repository content.
	err := os.WriteFile(path, content, filePermissions)
	if err != nil {
		return fmt.Errorf("write generated source %s: %w", path, err)
	}

	return nil
}

func checkFile(path string, expected []byte) error {
	// #nosec G304 -- path is a fixed generated source path.
	current, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("read generated source %s: %w", path, err)
	}

	if !bytes.Equal(current, expected) {
		return fmt.Errorf("%s: %w; run make generate-wire", path, errGeneratedDrift)
	}

	return nil
}

func fatal(err error) {
	_, _ = fmt.Fprintln(os.Stderr, err)

	os.Exit(1)
}
