// Command wiremodels bundles API components and generates responsibility-specific wire models.
package main

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"

	"gopkg.in/yaml.v3"
)

const sourceMode = 0o644
const yamlIndent = 2

var (
	errDuplicateSchema    = errors.New("schema appears in more than one model group")
	errMissingComponents  = errors.New("model source has no components.schemas")
	errGeneratedDrift     = errors.New("generated artifact differs from its schema")
	errMissingSchemaGroup = errors.New("model group has no schemas")
)

type modelGroup struct {
	Name       string   `json:"name"`
	Source     string   `json:"source"`
	Operations []string `json:"operations"`
}

type modelManifest struct {
	Input  string       `json:"input"`
	Groups []modelGroup `json:"groups"`
}

type modelSources struct {
	manifest modelManifest
	bundle   map[string]any
	owners   map[string]string
}

func main() {
	check := flag.Bool("check", false, "verify schema bundle and generator configurations")
	generate := flag.Bool("generate", false, "run the pinned model generator for every API responsibility")

	flag.Parse()

	err := run(*check, *generate)
	if err != nil {
		_, _ = fmt.Fprintln(os.Stderr, err)

		os.Exit(1)
	}
}

func run(check, generate bool) error {
	sources, err := loadModelSources()
	if err != nil {
		return err
	}

	err = writeModelBundle(sources, check)
	if err != nil {
		return err
	}

	for _, group := range sources.manifest.Groups {
		err = configureModelGroup(sources, group, check, generate)
		if err != nil {
			return err
		}
	}

	return nil
}

func readJSONManifest() (modelManifest, error) {
	data, err := os.ReadFile("api/model-groups.json")
	if err != nil {
		return modelManifest{}, fmt.Errorf("read model groups: %w", err)
	}

	var manifest modelManifest

	err = json.Unmarshal(data, &manifest)
	if err != nil {
		return modelManifest{}, fmt.Errorf("decode model groups: %w", err)
	}

	return manifest, nil
}

func readSchema(path string) (map[string]any, error) {
	// #nosec G304 -- paths come from the checked-in schema manifest.
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read schema %s: %w", path, err)
	}

	var document map[string]any

	err = yaml.Unmarshal(data, &document)
	if err != nil {
		return nil, fmt.Errorf("decode schema %s: %w", path, err)
	}

	return document, nil
}

func loadModelSources() (modelSources, error) {
	manifest, err := readJSONManifest()
	if err != nil {
		return modelSources{}, err
	}

	bundle, err := readSchema(manifest.Input)
	if err != nil {
		return modelSources{}, err
	}

	components, ok := bundle["components"].(map[string]any)
	if !ok {
		return modelSources{}, errMissingComponents
	}

	schemas := make(map[string]any)
	owners := make(map[string]string)

	for _, group := range manifest.Groups {
		err = addModelGroup(schemas, owners, group)
		if err != nil {
			return modelSources{}, err
		}
	}

	components["schemas"] = schemas

	err = validateModelOwnership(manifest, bundle)
	if err != nil {
		return modelSources{}, err
	}

	return modelSources{manifest: manifest, bundle: bundle, owners: owners}, nil
}

func addModelGroup(schemas map[string]any, owners map[string]string, group modelGroup) error {
	document, err := readSchema(group.Source)
	if err != nil {
		return err
	}

	components, hasComponents := document["components"].(map[string]any)
	if !hasComponents {
		return fmt.Errorf("%s: %w", group.Source, errMissingComponents)
	}

	definitions, ok := components["schemas"].(map[string]any)
	if !ok || len(definitions) == 0 {
		return fmt.Errorf("%s: %w", group.Source, errMissingSchemaGroup)
	}

	for name, definition := range definitions {
		if prior := owners[name]; prior != "" {
			return fmt.Errorf("%s (%s, %s): %w", name, prior, group.Name, errDuplicateSchema)
		}

		owners[name] = group.Name
		schemas[name] = definition
	}

	return nil
}

func writeModelBundle(sources modelSources, check bool) error {
	data, err := encodeYAML(sources.bundle)
	if err != nil {
		return fmt.Errorf("encode OpenAPI bundle: %w", err)
	}

	data = append([]byte("# Generated by tools/wiremodels from api/http.openapi.yaml and api/models/*.yaml. DO NOT EDIT.\n"), data...)

	return writeOrCheck("api/openapi.yaml", data, check)
}

func configureModelGroup(sources modelSources, group modelGroup, check, generate bool) error {
	excluded := make([]string, 0, len(sources.owners))

	for name, owner := range sources.owners {
		if owner != group.Name {
			excluded = append(excluded, name)
		}
	}

	sort.Strings(excluded)

	operations := group.Operations
	if len(operations) == 0 {
		operations = []string{"__component_only__"}
	}

	output := "pkg/dependencymodels/" + group.Name + ".gen.go"
	configuration := map[string]any{
		"package":  "tuyamodels",
		"generate": map[string]any{"models": true},
		"output":   output,
		"output-options": map[string]any{
			"skip-prune":            true,
			"include-operation-ids": operations,
			"exclude-schemas":       excluded,
		},
	}

	data, err := encodeYAML(configuration)
	if err != nil {
		return fmt.Errorf("encode model generator configuration: %w", err)
	}

	path := "pkg/dependencymodels/" + group.Name + ".config.yaml"

	err = writeOrCheck(path, data, check)
	if err != nil || !generate {
		return err
	}

	// #nosec G204 -- fixed generator/version and checked-in repository configuration.
	command := exec.CommandContext(
		context.Background(), "go", "run", "github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@v2.8.0",
		"-config", filepath.Clean(path), "api/openapi.yaml",
	)
	command.Stdout = os.Stdout
	command.Stderr = os.Stderr

	err = command.Run()
	if err != nil {
		return fmt.Errorf("generate %s models: %w", group.Name, err)
	}

	return nil
}

func writeOrCheck(path string, data []byte, check bool) error {
	if check {
		// #nosec G304 -- path is a fixed repository artifact or a checked manifest group.
		current, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("read artifact %s: %w", path, err)
		}

		if !bytes.Equal(current, data) {
			return fmt.Errorf("%s: %w", path, errGeneratedDrift)
		}

		return nil
	}

	// #nosec G306 -- generated schemas and Go configurations are public source artifacts.
	err := os.WriteFile(path, data, sourceMode)
	if err != nil {
		return fmt.Errorf("write artifact %s: %w", path, err)
	}

	return nil
}

func encodeYAML(value any) ([]byte, error) {
	var buffer bytes.Buffer

	encoder := yaml.NewEncoder(&buffer)
	encoder.SetIndent(yamlIndent)

	err := encoder.Encode(value)
	if err != nil {
		return nil, fmt.Errorf("encode YAML: %w", err)
	}

	err = encoder.Close()
	if err != nil {
		return nil, fmt.Errorf("close YAML encoder: %w", err)
	}

	return buffer.Bytes(), nil
}
