package main

import (
	"fmt"
	"go/format"
	"go/token"
	"sort"
	"strings"
	"unicode"
)

func generatePropertyConstants(bundle map[string]any) ([]byte, error) {
	components, hasComponents := bundle["components"].(map[string]any)
	if !hasComponents {
		return nil, fmt.Errorf("OpenAPI components are absent: %w", errModelOwnership)
	}

	schemas, hasSchemas := components["schemas"].(map[string]any)
	if !hasSchemas || len(schemas) == 0 {
		return nil, fmt.Errorf("OpenAPI schemas are absent: %w", errModelOwnership)
	}

	var output strings.Builder

	output.WriteString("// Code generated by tools/wiremodels from API model schemas; DO NOT EDIT.\n")
	output.WriteString("package tuyamodels\n\nconst (\n")

	state := propertyConstantWriter{
		output: &output, seen: make(map[string]string),
		queryValues: nil, headerValues: nil, count: 0,
	}
	for _, schemaName := range sortedPropertyNames(schemas) {
		err := state.writeSchema(schemaName, schemas[schemaName])
		if err != nil {
			return nil, err
		}
	}

	queryValues := state.queryValues
	headerValues := state.headerValues

	queryValues = append(queryValues, operationParameterKeys(bundle, "query")...)
	headerValues = append(headerValues, operationParameterKeys(bundle, "header")...)

	if state.count == 0 {
		return nil, fmt.Errorf("no component property names found: %w", errModelOwnership)
	}

	output.WriteString(")\n\n")

	err := writeKeyConstants(&output, queryValues)
	if err != nil {
		return nil, err
	}

	err = writeKeyConstants(&output, headerValues)
	if err != nil {
		return nil, err
	}

	writeKnownKeyPredicate(&output, "QueryParam", "IsKnownQueryParam", queryValues)
	writeKnownKeyPredicate(&output, "Header", "IsKnownHeader", headerValues)

	formatted, err := format.Source([]byte(output.String()))
	if err != nil {
		return nil, fmt.Errorf("format generated property constants: %w", err)
	}

	return formatted, nil
}

type propertyConstantWriter struct {
	output       *strings.Builder
	seen         map[string]string
	queryValues  []keyConstant
	headerValues []keyConstant
	count        int
}

func sortedPropertyNames(values map[string]any) []string {
	names := make([]string, 0, len(values))
	for name := range values {
		names = append(names, name)
	}

	sort.Strings(names)

	return names
}

func (writer *propertyConstantWriter) writeSchema(schemaName string, rawSchema any) error {
	schema, valid := rawSchema.(map[string]any)
	if !valid {
		return fmt.Errorf("component %q is not an object schema: %w", schemaName, errModelOwnership)
	}

	properties, hasProperties := schema["properties"].(map[string]any)
	if !hasProperties {
		return nil
	}

	for _, propertyName := range sortedPropertyNames(properties) {
		err := writer.writeProperty(schemaName, propertyName)
		if err != nil {
			return err
		}

		owner := schemaName + "." + propertyName
		if schema["x-go-tuya-query-keys"] == true {
			writer.queryValues = append(writer.queryValues, keyConstant{
				name: "QueryParam" + propertyIdentifier(propertyName), value: propertyName, owner: owner,
			})
		}

		if schema["x-go-tuya-header-keys"] == true {
			writer.headerValues = append(writer.headerValues, keyConstant{
				name: "Header" + propertyIdentifier(propertyName), value: propertyName, owner: owner,
			})
		}
	}

	return nil
}

func (writer *propertyConstantWriter) writeProperty(schemaName, propertyName string) error {
	identifier := "Property" + schemaName + propertyIdentifier(propertyName)
	if !token.IsIdentifier(identifier) {
		return fmt.Errorf("component %q property %q has invalid key constant name %q: %w",
			schemaName, propertyName, identifier, errModelOwnership)
	}

	if prior := writer.seen[identifier]; prior != "" {
		return fmt.Errorf("properties %q and %q collide as %q: %w",
			prior, schemaName+"."+propertyName, identifier, errModelOwnership)
	}

	writer.seen[identifier] = schemaName + "." + propertyName
	fmt.Fprintf(writer.output, "\t%s = %q\n", identifier, propertyName)

	writer.count++

	return nil
}

type keyConstant struct {
	name  string
	value string
	owner string
}

func operationParameterKeys(bundle map[string]any, parameterLocation string) []keyConstant {
	paths, _ := bundle["paths"].(map[string]any)

	var constants []keyConstant

	for path, rawPath := range paths {
		operations, _ := rawPath.(map[string]any)
		for method, rawOperation := range operations {
			operation, _ := rawOperation.(map[string]any)

			parameters, _ := operation["parameters"].([]any)

			for _, rawParameter := range parameters {
				parameter, _ := rawParameter.(map[string]any)
				name, _ := parameter["name"].(string)

				location, _ := parameter["in"].(string)

				if name == "" || location != parameterLocation {
					continue
				}

				prefix := "QueryParam"
				if parameterLocation == "header" {
					prefix = "Header"
				}

				operationID, _ := operation["operationId"].(string)
				if operationID == "" {
					operationID = method + " " + path
				}

				constants = append(constants, keyConstant{
					name:  prefix + propertyIdentifier(name),
					value: name,
					owner: operationID,
				})
			}
		}
	}

	return constants
}

func writeKeyConstants(output *strings.Builder, constants []keyConstant) error {
	if len(constants) == 0 {
		return nil
	}

	valuesByName, err := groupKeyConstants(constants)
	if err != nil {
		return err
	}

	constantValues, err := resolveKeyConstants(valuesByName)
	if err != nil {
		return err
	}

	names := make([]string, 0, len(constantValues))
	for name := range constantValues {
		names = append(names, name)
	}

	sort.Strings(names)

	output.WriteString("const (\n")

	for _, name := range names {
		fmt.Fprintf(output, "\t%s = %q\n", name, constantValues[name])
	}

	output.WriteString(")\n\n")

	return nil
}

func groupKeyConstants(constants []keyConstant) (map[string]map[string][]string, error) {
	valuesByName := make(map[string]map[string][]string)

	for _, constant := range constants {
		if !token.IsIdentifier(constant.name) || constant.value == "" {
			return nil, fmt.Errorf("schema owner %q has invalid query/header key %q: %w", constant.owner, constant.value, errModelOwnership)
		}

		if valuesByName[constant.name] == nil {
			valuesByName[constant.name] = make(map[string][]string)
		}

		valuesByName[constant.name][constant.value] = append(valuesByName[constant.name][constant.value], constant.owner)
	}

	return valuesByName, nil
}

func resolveKeyConstants(valuesByName map[string]map[string][]string) (map[string]string, error) {
	constantValues := make(map[string]string)

	for baseName, values := range valuesByName {
		if len(values) == 1 {
			for value := range values {
				constantValues[baseName] = value
			}

			continue
		}

		for value, owners := range values {
			sort.Strings(owners)

			name := baseName + "For" + propertyIdentifier(owners[0])
			if !token.IsIdentifier(name) || constantValues[name] != "" {
				return nil, fmt.Errorf("conflicting query/header key constant %q: %w", name, errModelOwnership)
			}

			constantValues[name] = value
		}
	}

	return constantValues, nil
}

func writeKnownKeyPredicate(output *strings.Builder, variableName, functionName string, constants []keyConstant) {
	values := make(map[string]bool, len(constants))
	for _, constant := range constants {
		values[constant.value] = true
	}

	keys := make([]string, 0, len(values))
	for value := range values {
		keys = append(keys, value)
	}

	sort.Strings(keys)

	fmt.Fprintf(output, "var known%s = map[string]struct{}{\n", variableName)

	for _, key := range keys {
		fmt.Fprintf(output, "\t%q: {},\n", key)
	}

	output.WriteString("}\n\n")
	fmt.Fprintf(output, "func %s(name string) bool { _, ok := known%s[name]; return ok }\n\n", functionName, variableName)
}

func propertyIdentifier(name string) string {
	var output strings.Builder

	upperNext := true

	for _, character := range name {
		if !unicode.IsLetter(character) && !unicode.IsDigit(character) {
			upperNext = true

			continue
		}

		if upperNext {
			output.WriteRune(unicode.ToUpper(character))

			upperNext = false

			continue
		}

		output.WriteRune(character)
	}

	return output.String()
}
