// Package wire provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package wire

import (
	"encoding/json"
	"fmt"
)

// DeviceListEnvelope The reference identifies the result member as BaseDeviceInfoRes. The sample omits envelope metadata; unspecified fields are left open.
type DeviceListEnvelope struct {
	// Result Tuya documents total, devices, and last_id as the result fields. The reference does not state which are required in every response.
	Result               *DeviceListResult      `json:"result,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// DeviceListResult Tuya documents total, devices, and last_id as the result fields. The reference does not state which are required in every response.
type DeviceListResult struct {
	Devices *[]DeviceRecord `json:"devices,omitempty"`

	// LastId Last query ID for device pagination.
	LastId *string `json:"last_id,omitempty"`

	// Total Total number of entries.
	Total                *int64                 `json:"total,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// DeviceRecord Fields below appear in Tuya's official example response for this operation. The reference does not define requiredness or an exhaustive field set. Additional properties are retained for forward compatibility.
type DeviceRecord struct {
	// ActiveTime Activation timestamp value in the example response.
	ActiveTime *int64 `json:"active_time,omitempty"`

	// BizType Business type value in the example response.
	BizType *int `json:"biz_type,omitempty"`

	// Category Product category in the example response.
	Category *string `json:"category,omitempty"`

	// CreateTime Creation timestamp value in the example response.
	CreateTime *int64 `json:"create_time,omitempty"`

	// Icon Device icon path in the example response.
	Icon *string `json:"icon,omitempty"`

	// Id Device identifier in the example response.
	Id *string `json:"id,omitempty"`

	// Ip IP address in the example response.
	Ip *string `json:"ip,omitempty"`

	// LocalKey Local key field shown in Tuya's example. Treat values as secrets and never log or publish them.
	LocalKey *string `json:"local_key,omitempty"`

	// Model Product model in the example response.
	Model *string `json:"model,omitempty"`

	// Name Device name in the example response.
	Name *string `json:"name,omitempty"`

	// Online Online state in the example response.
	Online *bool `json:"online,omitempty"`

	// OwnerId Device owner identifier in the example response.
	OwnerId *string `json:"owner_id,omitempty"`

	// ProductId Product identifier in the example response.
	ProductId *string `json:"product_id,omitempty"`

	// ProductName Product name in the example response.
	ProductName *string         `json:"product_name,omitempty"`
	Status      *[]DeviceStatus `json:"status,omitempty"`

	// Sub Whether the device is a sub-device in the example response.
	Sub *bool `json:"sub,omitempty"`

	// TimeZone Time zone string in the example response.
	TimeZone *string `json:"time_zone,omitempty"`

	// Uid User identifier in the example response.
	Uid *string `json:"uid,omitempty"`

	// UpdateTime Update timestamp value in the example response.
	UpdateTime *int64 `json:"update_time,omitempty"`

	// Uuid Device UUID in the example response.
	Uuid                 *string                `json:"uuid,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// DeviceStatus A status entry in Tuya's example response. The example uses a string value; the reference does not constrain the value type, so it remains an unconstrained JSON value.
type DeviceStatus struct {
	// Code Status code in the example response.
	Code                 *string                `json:"code,omitempty"`
	Value                interface{}            `json:"value,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// GetDeviceListParams defines parameters for GetDeviceList.
type GetDeviceListParams struct {
	// DeviceIds Comma-separated device IDs.
	DeviceIds *string `form:"device_ids,omitempty" json:"device_ids,omitempty"`

	// ProductId Product ID filter.
	ProductId *string `form:"product_id,omitempty" json:"product_id,omitempty"`

	// Schema Unique application identifier.
	Schema *string `form:"schema,omitempty" json:"schema,omitempty"`

	// LastId Last query ID for device pagination.
	LastId *string `form:"last_id,omitempty" json:"last_id,omitempty"`

	// PageSize Number of entries returned per page.
	PageSize int `form:"page_size" json:"page_size"`

	// PageNo Current page number.
	PageNo int `form:"page_no" json:"page_no"`

	// StartTime Start time for the query, as a 10-digit timestamp.
	StartTime *int64 `form:"start_time,omitempty" json:"start_time,omitempty"`

	// EndTime End time for the query, as a 10-digit timestamp.
	EndTime *int64 `form:"end_time,omitempty" json:"end_time,omitempty"`
}

// Getter for additional properties for DeviceListEnvelope. Returns the specified
// element and whether it was found
func (a DeviceListEnvelope) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for DeviceListEnvelope
func (a *DeviceListEnvelope) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for DeviceListEnvelope to handle AdditionalProperties
func (a *DeviceListEnvelope) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["result"]; found {
		err = json.Unmarshal(raw, &a.Result)
		if err != nil {
			return fmt.Errorf("error reading 'result': %w", err)
		}
		delete(object, "result")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for DeviceListEnvelope to handle AdditionalProperties
func (a DeviceListEnvelope) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Result != nil {
		object["result"], err = json.Marshal(a.Result)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'result': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for DeviceListResult. Returns the specified
// element and whether it was found
func (a DeviceListResult) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for DeviceListResult
func (a *DeviceListResult) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for DeviceListResult to handle AdditionalProperties
func (a *DeviceListResult) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["devices"]; found {
		err = json.Unmarshal(raw, &a.Devices)
		if err != nil {
			return fmt.Errorf("error reading 'devices': %w", err)
		}
		delete(object, "devices")
	}

	if raw, found := object["last_id"]; found {
		err = json.Unmarshal(raw, &a.LastId)
		if err != nil {
			return fmt.Errorf("error reading 'last_id': %w", err)
		}
		delete(object, "last_id")
	}

	if raw, found := object["total"]; found {
		err = json.Unmarshal(raw, &a.Total)
		if err != nil {
			return fmt.Errorf("error reading 'total': %w", err)
		}
		delete(object, "total")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for DeviceListResult to handle AdditionalProperties
func (a DeviceListResult) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Devices != nil {
		object["devices"], err = json.Marshal(a.Devices)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'devices': %w", err)
		}
	}

	if a.LastId != nil {
		object["last_id"], err = json.Marshal(a.LastId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'last_id': %w", err)
		}
	}

	if a.Total != nil {
		object["total"], err = json.Marshal(a.Total)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'total': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for DeviceRecord. Returns the specified
// element and whether it was found
func (a DeviceRecord) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for DeviceRecord
func (a *DeviceRecord) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for DeviceRecord to handle AdditionalProperties
func (a *DeviceRecord) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["active_time"]; found {
		err = json.Unmarshal(raw, &a.ActiveTime)
		if err != nil {
			return fmt.Errorf("error reading 'active_time': %w", err)
		}
		delete(object, "active_time")
	}

	if raw, found := object["biz_type"]; found {
		err = json.Unmarshal(raw, &a.BizType)
		if err != nil {
			return fmt.Errorf("error reading 'biz_type': %w", err)
		}
		delete(object, "biz_type")
	}

	if raw, found := object["category"]; found {
		err = json.Unmarshal(raw, &a.Category)
		if err != nil {
			return fmt.Errorf("error reading 'category': %w", err)
		}
		delete(object, "category")
	}

	if raw, found := object["create_time"]; found {
		err = json.Unmarshal(raw, &a.CreateTime)
		if err != nil {
			return fmt.Errorf("error reading 'create_time': %w", err)
		}
		delete(object, "create_time")
	}

	if raw, found := object["icon"]; found {
		err = json.Unmarshal(raw, &a.Icon)
		if err != nil {
			return fmt.Errorf("error reading 'icon': %w", err)
		}
		delete(object, "icon")
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if raw, found := object["ip"]; found {
		err = json.Unmarshal(raw, &a.Ip)
		if err != nil {
			return fmt.Errorf("error reading 'ip': %w", err)
		}
		delete(object, "ip")
	}

	if raw, found := object["local_key"]; found {
		err = json.Unmarshal(raw, &a.LocalKey)
		if err != nil {
			return fmt.Errorf("error reading 'local_key': %w", err)
		}
		delete(object, "local_key")
	}

	if raw, found := object["model"]; found {
		err = json.Unmarshal(raw, &a.Model)
		if err != nil {
			return fmt.Errorf("error reading 'model': %w", err)
		}
		delete(object, "model")
	}

	if raw, found := object["name"]; found {
		err = json.Unmarshal(raw, &a.Name)
		if err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
		delete(object, "name")
	}

	if raw, found := object["online"]; found {
		err = json.Unmarshal(raw, &a.Online)
		if err != nil {
			return fmt.Errorf("error reading 'online': %w", err)
		}
		delete(object, "online")
	}

	if raw, found := object["owner_id"]; found {
		err = json.Unmarshal(raw, &a.OwnerId)
		if err != nil {
			return fmt.Errorf("error reading 'owner_id': %w", err)
		}
		delete(object, "owner_id")
	}

	if raw, found := object["product_id"]; found {
		err = json.Unmarshal(raw, &a.ProductId)
		if err != nil {
			return fmt.Errorf("error reading 'product_id': %w", err)
		}
		delete(object, "product_id")
	}

	if raw, found := object["product_name"]; found {
		err = json.Unmarshal(raw, &a.ProductName)
		if err != nil {
			return fmt.Errorf("error reading 'product_name': %w", err)
		}
		delete(object, "product_name")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if raw, found := object["sub"]; found {
		err = json.Unmarshal(raw, &a.Sub)
		if err != nil {
			return fmt.Errorf("error reading 'sub': %w", err)
		}
		delete(object, "sub")
	}

	if raw, found := object["time_zone"]; found {
		err = json.Unmarshal(raw, &a.TimeZone)
		if err != nil {
			return fmt.Errorf("error reading 'time_zone': %w", err)
		}
		delete(object, "time_zone")
	}

	if raw, found := object["uid"]; found {
		err = json.Unmarshal(raw, &a.Uid)
		if err != nil {
			return fmt.Errorf("error reading 'uid': %w", err)
		}
		delete(object, "uid")
	}

	if raw, found := object["update_time"]; found {
		err = json.Unmarshal(raw, &a.UpdateTime)
		if err != nil {
			return fmt.Errorf("error reading 'update_time': %w", err)
		}
		delete(object, "update_time")
	}

	if raw, found := object["uuid"]; found {
		err = json.Unmarshal(raw, &a.Uuid)
		if err != nil {
			return fmt.Errorf("error reading 'uuid': %w", err)
		}
		delete(object, "uuid")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for DeviceRecord to handle AdditionalProperties
func (a DeviceRecord) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.ActiveTime != nil {
		object["active_time"], err = json.Marshal(a.ActiveTime)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'active_time': %w", err)
		}
	}

	if a.BizType != nil {
		object["biz_type"], err = json.Marshal(a.BizType)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'biz_type': %w", err)
		}
	}

	if a.Category != nil {
		object["category"], err = json.Marshal(a.Category)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'category': %w", err)
		}
	}

	if a.CreateTime != nil {
		object["create_time"], err = json.Marshal(a.CreateTime)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'create_time': %w", err)
		}
	}

	if a.Icon != nil {
		object["icon"], err = json.Marshal(a.Icon)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'icon': %w", err)
		}
	}

	if a.Id != nil {
		object["id"], err = json.Marshal(a.Id)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'id': %w", err)
		}
	}

	if a.Ip != nil {
		object["ip"], err = json.Marshal(a.Ip)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'ip': %w", err)
		}
	}

	if a.LocalKey != nil {
		object["local_key"], err = json.Marshal(a.LocalKey)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'local_key': %w", err)
		}
	}

	if a.Model != nil {
		object["model"], err = json.Marshal(a.Model)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'model': %w", err)
		}
	}

	if a.Name != nil {
		object["name"], err = json.Marshal(a.Name)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'name': %w", err)
		}
	}

	if a.Online != nil {
		object["online"], err = json.Marshal(a.Online)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'online': %w", err)
		}
	}

	if a.OwnerId != nil {
		object["owner_id"], err = json.Marshal(a.OwnerId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'owner_id': %w", err)
		}
	}

	if a.ProductId != nil {
		object["product_id"], err = json.Marshal(a.ProductId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'product_id': %w", err)
		}
	}

	if a.ProductName != nil {
		object["product_name"], err = json.Marshal(a.ProductName)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'product_name': %w", err)
		}
	}

	if a.Status != nil {
		object["status"], err = json.Marshal(a.Status)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'status': %w", err)
		}
	}

	if a.Sub != nil {
		object["sub"], err = json.Marshal(a.Sub)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'sub': %w", err)
		}
	}

	if a.TimeZone != nil {
		object["time_zone"], err = json.Marshal(a.TimeZone)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'time_zone': %w", err)
		}
	}

	if a.Uid != nil {
		object["uid"], err = json.Marshal(a.Uid)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'uid': %w", err)
		}
	}

	if a.UpdateTime != nil {
		object["update_time"], err = json.Marshal(a.UpdateTime)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'update_time': %w", err)
		}
	}

	if a.Uuid != nil {
		object["uuid"], err = json.Marshal(a.Uuid)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'uuid': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for DeviceStatus. Returns the specified
// element and whether it was found
func (a DeviceStatus) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for DeviceStatus
func (a *DeviceStatus) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for DeviceStatus to handle AdditionalProperties
func (a *DeviceStatus) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["code"]; found {
		err = json.Unmarshal(raw, &a.Code)
		if err != nil {
			return fmt.Errorf("error reading 'code': %w", err)
		}
		delete(object, "code")
	}

	if raw, found := object["value"]; found {
		err = json.Unmarshal(raw, &a.Value)
		if err != nil {
			return fmt.Errorf("error reading 'value': %w", err)
		}
		delete(object, "value")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for DeviceStatus to handle AdditionalProperties
func (a DeviceStatus) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Code != nil {
		object["code"], err = json.Marshal(a.Code)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'code': %w", err)
		}
	}

	object["value"], err = json.Marshal(a.Value)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'value': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
