// Code generated by tools/wireroutes from api/mqtt.asyncapi.yaml; DO NOT EDIT.
package wire

const (
	MQTTChannelDeviceLocal  = "{deviceTopic}/pen"
	MQTTChannelDeviceStatus = "{deviceTopic}/sta"
	MQTTChannelOwnerEvents  = "{ownerTopic}"
)
