// Code generated by tools/wireroutes from api/mqtt.asyncapi.yaml; DO NOT EDIT.
package wire

// MQTTChannel is a schema-defined subscription address template.
type MQTTChannel string

const (
	MQTTChannelDeviceLocal  MQTTChannel = "{deviceTopic}/pen"
	MQTTChannelDeviceStatus MQTTChannel = "{deviceTopic}/sta"
	MQTTChannelOwnerEvents  MQTTChannel = "{ownerTopic}"
)
